; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; License: CC BY-NC-SA 4.0 (Non-commercial use only)

#define MyAppName "Genizah Search Pro"
#define MyAppVersion "7.2.3"
#define MyAppPublisher "Hillel Gershuni / Dicta"
#define MyAppURL "https://www.GenizahSearch.com/"
#define MyAppExeName "GenizahSearchPro.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{97DDB4E4-46EA-4C2B-A429-68008DF777AB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
DisableDirPage=no
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\GenizahSearch\dist
OutputBaseFilename=GenizahSearchPro_V7.2.3_Setup
SetupIconFile=C:\GenizahSearch\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic
; Auto-update support: close running app and restart after update
CloseApplications=force
CloseApplicationsFilter=*.exe
RestartApplications=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"

[CustomMessages]
english.DownloadTranscriptions=Download Transcriptions File
hebrew.DownloadTranscriptions=להורדת קובץ התעתיקים
english.VisitWebsite=Visit Dicta Genizah Search website
hebrew.VisitWebsite=לאתר הגניזה של דיקטה

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\GenizahSearch\dist\GenizahSearchPro\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\GenizahSearch\dist\GenizahSearchPro\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall
Filename: "https://zenodo.org/records/17734473"; Description: "{cm:DownloadTranscriptions}"; Flags: postinstall shellexec nowait unchecked
Filename: "https://www.GenizahSearch.com/"; Description: "{cm:VisitWebsite}"; Flags: postinstall shellexec nowait unchecked
