# -*- coding: utf-8 -*-
"""Phase 105 EXPUX-03: LOCAL-only exports omit the MiDRASH/Zenodo credit.

Unit-tests the module-level credit helpers in ``shared.export_dossier`` —
no Qt / GenizahGUI instance required.
"""
import openpyxl

from shared.export_dossier import build_credits_info_sheet, credits_lines


_MIDRASH_MARKERS = ("Data Source", "Dataset", "Citation")


def _joined(lines):
    return "\n".join(lines)


# --- credits_lines ---------------------------------------------------------

def test_credits_lines_default_includes_midrash_en():
    text = _joined(credits_lines("en"))
    assert "Stoekl Ben Ezra" in text
    assert "10.5281/zenodo.17734473" in text


def test_credits_lines_default_includes_midrash_he():
    text = _joined(credits_lines("he"))
    assert "Stoekl Ben Ezra" in text  # citation never translated
    assert "10.5281/zenodo.17734473" in text


def test_credits_lines_local_only_omits_midrash_en():
    lines = credits_lines("en", local_only=True)
    text = _joined(lines)
    assert "Stoekl Ben Ezra" not in text
    assert "zenodo" not in text.lower()
    assert not any(ln.startswith(_MIDRASH_MARKERS) for ln in lines)
    # Attribution kept.
    assert any("Generated by" in ln for ln in lines)
    assert any("Creator" in ln for ln in lines)


def test_credits_lines_local_only_omits_midrash_he():
    lines = credits_lines("he", local_only=True)
    text = _joined(lines)
    assert "Stoekl Ben Ezra" not in text
    assert "zenodo" not in text.lower()
    # Hebrew attribution lines kept ("הופק על ידי" / "יוצר").
    assert any("הופק על ידי" in ln for ln in lines)
    assert any("יוצר" in ln for ln in lines)


def test_credits_lines_returns_fresh_copy():
    a = credits_lines("en")
    a.append("MUTATED")
    b = credits_lines("en")
    assert "MUTATED" not in b


# --- build_credits_info_sheet ---------------------------------------------

def _all_cell_text(ws):
    out = []
    for row in ws.iter_rows():
        for cell in row:
            if cell.value is not None:
                out.append(str(cell.value))
    return "\n".join(out)


def test_credits_sheet_local_only_omits_midrash():
    wb = openpyxl.Workbook()
    ws = wb.active
    build_credits_info_sheet(ws, lang="en", search_query="q", result_count=3, local_only=True)
    text = _all_cell_text(ws)
    assert "Stoekl Ben Ezra" not in text
    assert "10.5281/zenodo.17734473" not in text
    # Generated-by attribution + search metadata still present.
    assert "Generated by" in text
    assert "q" in text


def test_credits_sheet_default_keeps_midrash():
    wb = openpyxl.Workbook()
    ws = wb.active
    build_credits_info_sheet(ws, lang="en", search_query="q", result_count=3)
    text = _all_cell_text(ws)
    assert "Stoekl Ben Ezra" in text
    assert "10.5281/zenodo.17734473" in text
