# -*- coding: utf-8 -*-
"""Phase 96 D-F4: detect-then-fallback PDF extraction regression tests.

Implementation plan: 96-02-PLAN.md

Fixture notes (REVISION 2026-05-24 — prior executor discovery):
  - `single_word_per_line.pdf` is a synthetic fixture generated by
    `scripts/generate_single_word_fixture.py`. It places each word at a
    distinct x-position on the same visual line but writes them in scrambled
    content-stream order. PyMuPDF's blocks mode follows content-stream order
    (one-word-per-block, ratio 1.0), while `get_text("text", sort=True)` sorts
    by (y, x) coordinates and reconstructs the visual line order (ratio 0.0).
  - `clean_sample.pdf` is a synthetic fixture (generated by the same script)
    with normal paragraph text written via `page.insert_text()`. Blocks mode
    produces multi-word paragraphs (ratio 0.0) — the fallback NEVER fires.
    Used for `test_good_pdf_does_not_invoke_fallback_mode` (Codex MEDIUM #8).
  - `hebrew_sample.pdf` (Phase 95 fixture) is itself ~97% single-word in blocks
    mode (RTL Hebrew encoded character-by-character in the content stream).
    The fallback DOES fire for it and improves output. We no longer use it as
    the "clean control" for mode-spy tests (REVISION 2026-05-24 discovery).
    It IS used in `test_pathological_pdf_uses_fallback` as evidence the fallback
    fires and improves ratio on a real-world pathological PDF.
"""
import os
import pytest

FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures", "local_indexer")
SINGLE_WORD_PDF = os.path.join(FIXTURES_DIR, "single_word_per_line.pdf")
CLEAN_PDF = os.path.join(FIXTURES_DIR, "clean_sample.pdf")
HEBREW_PDF = os.path.join(FIXTURES_DIR, "hebrew_sample.pdf")


def _import_indexer_helpers():
    """Import the Phase 96 detection helper + extractor."""
    from shared.local_indexer import (
        extract_pdf_pages,
        _detect_single_word_per_line,
    )
    return extract_pdf_pages, _detect_single_word_per_line


def test_pathological_pdf_uses_fallback():
    """D-F4: extract_pdf_pages on single_word_per_line.pdf must trigger the
    `get_text('text', sort=True)` fallback and return paragraph-shaped text
    (NOT one-word-per-line).

    Fixture: `single_word_per_line.pdf` — blocks mode ratio >= 0.70, fallback
    via sort=True lowers ratio to 0.0 (all multi-word visual lines).
    """
    extract_pdf_pages, _ = _import_indexer_helpers()
    if not os.path.exists(SINGLE_WORD_PDF):
        pytest.fail(
            "Phase 96 Wave 0 fixture missing: " + SINGLE_WORD_PDF + "\n"
            "Run scripts/generate_single_word_fixture.py to regenerate."
        )
    pages = list(extract_pdf_pages(SINGLE_WORD_PDF))
    assert len(pages) >= 1
    page_num, text, title = pages[0]
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if len(lines) < 5:
        pytest.skip("Sample too small for ratio check")
    single = sum(1 for ln in lines if len(ln.split()) <= 1)
    ratio = single / len(lines)
    # After fallback, ratio should drop well below the 0.70 trigger threshold.
    assert ratio < 0.50, (
        f"Fallback did NOT produce paragraph-shaped text "
        f"(single_word_ratio={ratio:.2f}, expected < 0.50)"
    )


def test_good_pdf_stays_blocks():
    """D-F4 regression-direction-two: clean_sample.pdf (a synthetic PDF with
    proper multi-word paragraphs) must NOT trip the single-word detector.

    REVISION 2026-05-24: changed control fixture from hebrew_sample.pdf to
    clean_sample.pdf. The hebrew_sample.pdf fixture is itself ~97% single-word
    in blocks mode (real-world pathological), so it cannot serve as the clean
    control. clean_sample.pdf is a synthetic fixture created by insert_text()
    calls that produce proper multi-word blocks (ratio 0.0 in blocks mode).
    The fallback should NOT fire.
    """
    extract_pdf_pages, detect = _import_indexer_helpers()
    if not os.path.exists(CLEAN_PDF):
        pytest.fail(
            "Phase 96 clean_sample.pdf fixture missing: " + CLEAN_PDF + "\n"
            "Run scripts/generate_single_word_fixture.py to regenerate."
        )
    pages = list(extract_pdf_pages(CLEAN_PDF))
    assert len(pages) > 0
    for _p, text, _t in pages:
        lines = [ln for ln in text.splitlines() if ln.strip()]
        if len(lines) >= 5:
            assert not detect(text), (
                "False positive: clean_sample.pdf should NOT trip "
                "single-word-per-line detection (ratio should be 0.0)"
            )


def test_small_sample_skipped():
    """D-F4: detection heuristic returns False when < 5 non-empty lines
    (small-sample guard per RESEARCH §2)."""
    _, detect = _import_indexer_helpers()
    # 4 single-word lines: below the threshold sample size — must NOT trip.
    text = "one\ntwo\nthree\nfour\n"
    assert detect(text) is False, (
        "Small-sample guard failed: < 5 lines should skip detection"
    )


def test_good_pdf_does_not_invoke_fallback_mode():
    """Phase 96 D-F4 — Codex MEDIUM #8 closure (REVISION 2026-05-24).

    Stronger version of test_good_pdf_stays_blocks. The earlier test asserts
    extracted output is not pathological (single_word_ratio < detector threshold).
    This test additionally proves the FALLBACK PATH was not invoked on a clean
    PDF — i.e., page.get_text("text", sort=True) was never called.

    Why both tests: a buggy implementation could fall through to the
    fallback unnecessarily AND still produce a ratio < 0.50; the earlier
    test would pass. This test fails in that case.

    Fixture: clean_sample.pdf (synthetic, ratio 0.0 in blocks mode).
    hebrew_sample.pdf was rejected as the control because it IS pathological
    in blocks mode (REVISION 2026-05-24 prior executor discovery).

    Strategy: use unittest.mock to wrap fitz.Page.get_text, record each
    call's mode argument, then assert ("text", sort=True) was never the call
    signature for any page of clean_sample.pdf.

    Implementation plan: 96-02-PLAN.md (REVISION 2026-05-24).
    """
    import fitz
    from unittest.mock import patch

    extract_pdf_pages, _ = _import_indexer_helpers()
    if not os.path.exists(CLEAN_PDF):
        pytest.skip("clean_sample.pdf fixture not found")

    invoked_calls = []  # list of (mode, sort) tuples

    original_get_text = fitz.Page.get_text

    def _spy_get_text(self, *args, **kwargs):
        mode = args[0] if args else kwargs.get("option", None)
        sort = kwargs.get("sort", False)
        invoked_calls.append((mode, sort))
        return original_get_text(self, *args, **kwargs)

    with patch.object(fitz.Page, "get_text", _spy_get_text):
        pages = list(extract_pdf_pages(CLEAN_PDF))

    assert len(pages) > 0, "clean_sample.pdf should extract at least 1 page"

    # PRIMARY path uses get_text("blocks"). Confirm it was called.
    modes_called = [c[0] for c in invoked_calls]
    assert "blocks" in modes_called, (
        "Phase 96 D-F4 regression: primary blocks-mode extraction was never invoked"
    )

    # CRITICAL Codex MEDIUM #8 assertion: the FALLBACK path
    # (get_text("text", sort=True)) MUST NOT be invoked for clean PDFs.
    fallback_invocations = [
        i for i, (m, s) in enumerate(invoked_calls)
        if m == "text" and s is True
    ]
    assert not fallback_invocations, (
        f"Codex MEDIUM #8 regression: clean_sample.pdf (a synthetic clean PDF) "
        f"triggered the get_text('text', sort=True) fallback. "
        f"The detection heuristic is over-triggering. "
        f"All invocations: {invoked_calls}"
    )
