# -*- coding: utf-8 -*-
"""Attach the known-work registry to the v5 review db (dedup plan v2, step 1).

Consumes the FOUR hash-pinned step-0 inputs (verified against PINS.json,
fail-closed) and materializes:

  known_work         - minted known works (kw_id = 'kw' + sha256(anchor)[:12])
  known_work_member  - witnesses at (work_id, scope) grain; scope 'whole' or a
                       named division; container files carry a scope_prefix that
                       routes their rows by locus_label (longest-prefix rule)
  known_work_assertion - census members with no evidence rows (identity
                       assertions only; NEVER minted as witnesses)
  work_relation      - non-identity edges (shares_material)

Identity semantics (owner-ratified, Codex GO-WITH-FIXES):
  * census merges + same_work links + owner work-groups union into witness
    clusters; anthology containers NEVER union (their rows route per scope).
  * container_is_work: the family is the known work; contained parts are
    division-scoped witnesses; the container file is a whole-scope witness.
  * anthology: each division is (part of) its own known work per the scope map;
    NO union across parts.
  * gates: every witness maps to exactly one known work; per work either one
    'whole' member or only scoped members; no cluster spans two families; no
    cluster merges two census canonicals; every routed row matches a prefix.

Run (review server STOPPED):
    python -X utf8 scripts/build_work_registry.py
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sqlite3
import sys
from collections import Counter, defaultdict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_INPUTS = os.path.join(REPO_ROOT, "_tmp", "work_alias", "registry_inputs")

DDL = [
    """CREATE TABLE known_work(
  kw_id TEXT PRIMARY KEY,
  anchor TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  author TEXT,
  author_basis TEXT NOT NULL CHECK (author_basis IN
    ('owner_ruling','authority','none')),
  title_basis TEXT NOT NULL CHECK (title_basis IN
    ('census_canonical','owner_merge','family','work_group','mint','singleton',
     'cluster')),
  provisional INTEGER NOT NULL DEFAULT 0,
  main_witness_work TEXT,
  main_witness_scope TEXT,
  main_witness_basis TEXT NOT NULL DEFAULT 'default'
)""",
    """CREATE TABLE known_work_member(
  kw_id TEXT NOT NULL REFERENCES known_work(kw_id),
  work_id TEXT NOT NULL,
  scope TEXT NOT NULL,
  scope_prefix TEXT,
  basis TEXT NOT NULL CHECK (basis IN
    ('census','owner_merge','same_work_link','work_group','family_part',
     'family_container','scope_map','singleton')),
  route_basis TEXT CHECK (route_basis IN
    ('verified_link','division_title','pending_owner')),
  evidence_rows INTEGER NOT NULL,
  PRIMARY KEY (work_id, scope)
)""",
    """CREATE TABLE known_work_assertion(
  kw_id TEXT NOT NULL REFERENCES known_work(kw_id),
  work_id TEXT NOT NULL PRIMARY KEY,
  note TEXT
)""",
    """CREATE TABLE work_relation(
  work_a TEXT NOT NULL,
  work_b TEXT NOT NULL,
  relation TEXT NOT NULL CHECK (relation IN ('shares_material')),
  note TEXT,
  PRIMARY KEY (work_a, work_b, relation)
)""",
]

DOC = ("Known-work registry: every corpus work maps to exactly one known work "
       "(dedup registry, owner-ratified 2026-09-01). A known work has one main "
       "witness (citation of record) and any number of scoped witnesses; scoped "
       "members of container files route rows by locus_label longest-prefix. "
       "Identity is NEVER merged at the row level -- offsets keep their raw "
       "file. work_relation carries non-identity (shares_material) edges. "
       "basis='owner_merge' marks a whole-work identity the owner ruled for "
       "this artifact, on top of (never inside) the pinned upstream census.")


class GateError(SystemExit):
    pass


def kw_id_of(anchor: str) -> str:
    return "kw" + hashlib.sha256(anchor.encode("utf-8")).hexdigest()[:12]


# ---------------------------------------------------------------------------
# structural contract for the four pinned inputs
#
# The pinned docs are generated by build_inputs.py, but the owner rulings
# inside it are hand-authored literals -- so a future editing session can hand
# this builder a doc of the wrong SHAPE (a blank name, a string where a boolean
# belongs, two target keys, a typo'd key). Seven Codex review rounds produced
# one such anecdote after another; this validator closes the class in one
# place, BEFORE any semantic logic runs, so every gate below reasons about
# well-typed input only.
# ---------------------------------------------------------------------------

def _s(v, path):
    """A non-blank string (a blank name silently becomes a blank title)."""
    if not isinstance(v, str) or not v.strip():
        raise GateError(f"input contract: {path} must be a non-blank string, "
                        f"got {v!r}")
    return v


def _b(v, path):
    """A REAL boolean: the string 'false' is truthy and would authorize an
    override reserved for an explicit true (Codex round-7 HIGH-2)."""
    if not isinstance(v, bool):
        raise GateError(f"input contract: {path} must be a boolean, got {v!r} "
                        f"({type(v).__name__})")
    return v


def _i(v, path, minimum=None):
    if isinstance(v, bool) or not isinstance(v, int):
        raise GateError(f"input contract: {path} must be an integer, got {v!r}")
    if minimum is not None and v < minimum:
        raise GateError(f"input contract: {path} must be >= {minimum}, got {v}")
    return v


def _enum(v, path, allowed):
    if v not in allowed:
        raise GateError(f"input contract: {path} must be one of "
                        f"{sorted(allowed)}, got {v!r}")
    return v


def _obj(v, path, required, optional=()):
    """An object with EXACTLY the required keys plus any of the optional ones:
    an unknown key is a typo'd ruling, not a comment."""
    if not isinstance(v, dict):
        raise GateError(f"input contract: {path} must be an object, got {v!r}")
    missing = sorted(set(required) - set(v))
    unknown = sorted(set(v) - set(required) - set(optional))
    if missing or unknown:
        raise GateError(f"input contract: {path} keys wrong -- missing "
                        f"{missing}, unknown {unknown}")
    return v


def _lst(v, path, item):
    if not isinstance(v, list):
        raise GateError(f"input contract: {path} must be a list, got {v!r}")
    for i, x in enumerate(v):
        item(x, f"{path}[{i}]")
    return v


def _dct(v, path, val, key=_s):
    if not isinstance(v, dict):
        raise GateError(f"input contract: {path} must be an object, got {v!r}")
    for k, x in v.items():
        key(k, f"{path} key {k!r}")
        val(x, f"{path}[{k!r}]")
    return v


def _hex64(v, path):
    _s(v, path)
    if len(v) != 64 or any(c not in "0123456789abcdef" for c in v):
        raise GateError(f"input contract: {path} must be a sha256 hex digest, "
                        f"got {v!r}")
    return v


def validate_inputs(docs):
    """Type/shape/enum contract over the four pinned docs. Raises GateError on
    the first violation, naming its JSON path."""
    f = docs["container_families.json"]
    _obj(f, "container_families", ("alias_fact_count", "alias_fact_sha256",
                                   "families", "owner_questions",
                                   "shares_material_edges", "work_groups"),
         ("gate", "generated", "semantics", "version"))
    _hex64(f["alias_fact_sha256"], "container_families.alias_fact_sha256")
    _i(f["alias_fact_count"], "container_families.alias_fact_count", 0)
    def _family(v, p):
        _obj(v, p, ("class", "container", "contains_parts", "family",
                    "same_work_partners"),
             ("container_title", "note", "ruling"))
        _s(v["container"], f"{p}.container")
        _s(v["family"], f"{p}.family")
        _enum(v["class"], f"{p}.class", {"container_is_work", "anthology"})
        _lst(v["contains_parts"], f"{p}.contains_parts", _s)
        _lst(v["same_work_partners"], f"{p}.same_work_partners", _s)
    _lst(f["families"], "container_families.families", _family)
    def _group(v, p):
        _obj(v, p, ("members", "overrides_census"), ("ruling", "note"))
        _dct(v["members"], f"{p}.members", _s)
        if not v["members"]:
            raise GateError(f"input contract: {p}.members is empty")
        _b(v["overrides_census"], f"{p}.overrides_census")
    _dct(f["work_groups"], "container_families.work_groups", _group)
    def _question(v, p):
        _obj(v, p, ("affected", "key", "ruling", "status"))
        _s(v["key"], f"{p}.key")
        _s(v["ruling"], f"{p}.ruling")
        # 'open'/'pending' are legal SHAPES -- load_pinned refuses them for
        # semantic reasons (an unruled question must not build an artifact)
        _enum(v["status"], f"{p}.status", {"ruled", "open", "pending"})
        _lst(v["affected"], f"{p}.affected", _s)
    _lst(f["owner_questions"], "container_families.owner_questions", _question)
    def _share(v, p):
        _obj(v, p, ("a", "b", "note"))
        _s(v["a"], f"{p}.a")
        _s(v["b"], f"{p}.b")
        _s(v["note"], f"{p}.note")
        if v["a"] == v["b"]:
            raise GateError(f"input contract: {p} relates {v['a']} to itself")
    _lst(f["shares_material_edges"], "container_families.shares_material_edges",
         _share)

    c = docs["census_members.json"]
    _obj(c, "census_members", ("merges", "non_materialized_members"),
         ("dropped_by_135", "generated", "owner_merges",
          "release_contract_version", "source_path", "source_sha256",
          "version"))
    def _merge(v, p):
        _obj(v, p, ("canonical", "members", "not_in_review_db"))
        _s(v["canonical"], f"{p}.canonical")
        _lst(v["members"], f"{p}.members", _s)
        _lst(v["not_in_review_db"], f"{p}.not_in_review_db", _s)
        if len(set(v["members"])) != len(v["members"]):
            raise GateError(f"input contract: {p}.members repeats an id")
    _lst(c["merges"], "census_members.merges", _merge)
    def _owner_merge(v, p):
        # an owner merge is an identity ASSERTION: it carries its own ruling
        # text, needs two real members, and names its head
        _obj(v, p, ("canonical", "members", "ruling"), ("note",))
        _s(v["canonical"], f"{p}.canonical")
        _s(v["ruling"], f"{p}.ruling")
        _lst(v["members"], f"{p}.members", _s)
        if len(set(v["members"])) != len(v["members"]):
            raise GateError(f"input contract: {p}.members repeats an id")
        if len(v["members"]) < 2:
            raise GateError(f"input contract: {p}.members merges fewer than two "
                            f"works: {v['members']}")
        if v["canonical"] not in v["members"]:
            raise GateError(f"input contract: {p}.canonical {v['canonical']} is "
                            f"not one of its members {v['members']}")
    _lst(c.get("owner_merges", []), "census_members.owner_merges", _owner_merge)
    _lst(c["non_materialized_members"], "census_members.non_materialized_members",
         _s)

    s = docs["scope_map.json"]
    _obj(s, "scope_map", ("containers",), ("generated", "rule", "version"))
    def _entry(v, p):
        _obj(v, p, ("basis", "prefix", "rows_matched", "target"),
             ("target_title", "note"))
        _s(v["prefix"], f"{p}.prefix")
        _enum(v["basis"], f"{p}.basis",
              {"verified_link", "division_title", "pending_owner"})
        _i(v["rows_matched"], f"{p}.rows_matched", 1)
        t = _obj(v["target"], f"{p}.target", (), ("work", "group", "mint"))
        if len(t) != 1:
            raise GateError(f"input contract: {p}.target must name exactly one "
                            f"of work/group/mint, got {sorted(t)}")
        _s(next(iter(t.values())), f"{p}.target value")
        if "target_title" in v:
            _s(v["target_title"], f"{p}.target_title")
    def _entries(v, p):
        _lst(v, p, _entry)
        if not v:
            raise GateError(f"input contract: {p} declares no scope entries")
    _dct(s["containers"], "scope_map.containers", _entries)

    a = docs["author_authority.json"]
    _obj(a, "author_authority", ("fills", "owner_author_rulings",
                                 "owner_title_rulings", "variants"),
         ("generated", "owner_rulings_from_artifact",
          "sanctioned_author_inequality", "source_module",
          "source_module_sha256", "style", "version"))
    _dct(a["variants"], "author_authority.variants", _s)
    def _fill(v, p):
        _obj(v, p, ("author", "provenance"))
        _s(v["author"], f"{p}.author")
        _s(v["provenance"], f"{p}.provenance")
    _dct(a["fills"], "author_authority.fills", _fill)
    def _author_ruling(v, p):
        # None is meaningful here: "this work has NO author" (owner ruling)
        if v is not None:
            _s(v, p)
    _dct(a["owner_author_rulings"], "author_authority.owner_author_rulings",
         _author_ruling)
    _dct(a["owner_title_rulings"], "author_authority.owner_title_rulings", _s)


def load_pinned(inputs_dir, pins_sha256=None):
    pins_raw = open(os.path.join(inputs_dir, "PINS.json"), "rb").read()
    pins_hash = hashlib.sha256(pins_raw).hexdigest()
    # trusted root: the operator-supplied hash of PINS.json itself; without it
    # a swapped input+manifest pair would verify (Codex registry review MED-3)
    if pins_sha256 and pins_hash != pins_sha256:
        raise GateError(f"PINS.json does not match the supplied trusted root: "
                        f"got {pins_hash[:16]}..")
    pins = json.loads(pins_raw)
    docs = {}
    for name, want in pins["files"].items():
        data = open(os.path.join(inputs_dir, name), "rb").read()
        got = hashlib.sha256(data).hexdigest()
        if got != want:
            raise GateError(f"PIN MISMATCH {name}: pinned {want[:12]}.. got {got[:12]}..")
        docs[name] = json.loads(data)
    missing = sorted({"container_families.json", "census_members.json",
                      "scope_map.json", "author_authority.json"} - set(docs))
    if missing:
        raise GateError(f"PINS.json does not pin the required inputs: {missing}")
    # shape/type contract BEFORE any semantics reads a value
    validate_inputs(docs)
    for q in docs["container_families.json"]["owner_questions"]:
        if q["status"] != "ruled":
            raise GateError(f"owner question {q['key']!r} is not ruled; refusing to build")
    return pins, pins_hash, docs


class UnionFind:
    def __init__(self):
        self.p = {}

    def find(self, x):
        self.p.setdefault(x, x)
        while self.p[x] != x:
            self.p[x] = self.p[self.p[x]]
            x = self.p[x]
        return x

    def union(self, a, b):
        self.p[self.find(a)] = self.find(b)


def check_membership_gates(members, meta):
    """Gates over the finished member list (kept separate so each can be
    exercised directly: the coverage gate is defense-in-depth and no pinned
    input can reach it once the anthology-set gate holds)."""
    seen = {}
    whole_or_scoped = defaultdict(set)
    covered = defaultdict(int)
    for anchor, wid, scope, prefix, basis, rbasis, rows in members:
        # every division scope must be a real name, whatever produced it (a
        # group declaration, a part title, a routed prefix) -- round-6 HIGH-2
        if not isinstance(scope, str) or not scope.strip():
            raise GateError(f"member {wid} ({basis}): blank/invalid scope {scope!r}")
        key = (wid, scope)
        if key in seen and seen[key] != anchor:
            raise GateError(f"witness {key} in two known works: {seen[key]} / {anchor}")
        seen[key] = anchor
        whole_or_scoped[wid].add(scope)
        covered[wid] += rows
    # physical-row coverage: each work's evidence rows are counted EXACTLY once
    # across its memberships -- a second membership double-counts them
    # (Codex round-6 HIGH-1)
    for wid, n in sorted(covered.items()):
        if n != meta[wid]["rows"]:
            raise GateError(f"{wid}: memberships cover {n} rows, db has "
                            f"{meta[wid]['rows']}")
    for wid, scopes in whole_or_scoped.items():
        if "whole" in scopes and len(scopes) > 1:
            raise GateError(f"{wid} is both a whole and a scoped witness: "
                            f"{sorted(scopes)}")
    unmapped = set(meta) - set(whole_or_scoped)
    if unmapped:
        raise GateError(f"{len(unmapped)} works unmapped: {sorted(unmapped)[:10]}")


def build(db_path, inputs_dir, say=print, pins_sha256=None):
    """Open the db, build, and close it on EVERY path.

    A refused build must not keep the file handle: on Windows the locked db
    then blocks the next attempt (Codex round-5 MED-3).
    """
    con = sqlite3.connect(db_path)
    try:
        return _build(con, inputs_dir, say=say, pins_sha256=pins_sha256)
    finally:
        try:
            con.close()
        except sqlite3.Error:
            pass


def _build(con, inputs_dir, say=print, pins_sha256=None):
    pins, pins_hash, docs = load_pinned(inputs_dir, pins_sha256)
    fams = docs["container_families.json"]
    census = docs["census_members.json"]
    scope_map = docs["scope_map.json"]
    authority = docs["author_authority.json"]
    variants = authority["variants"]
    fills = authority["fills"]
    author_rulings = authority["owner_author_rulings"]
    title_rulings = authority["owner_title_rulings"]

    families = {}
    for f in fams["families"]:
        # a typo'd class or a duplicate declaration must not silently drop a
        # family out of both semantic paths (Codex round-4 HIGH-1)
        if f["class"] not in ("container_is_work", "anthology"):
            raise GateError(f"family {f.get('family')!r}: unknown class "
                            f"{f['class']!r}")
        if f["container"] in families:
            raise GateError(f"duplicate family declaration for container "
                            f"{f['container']}")
        families[f["container"]] = f
    anth = {c for c, f in families.items() if f["class"] == "anthology"}
    ciw = {c: f for c, f in families.items() if f["class"] == "container_is_work"}
    groups = fams["work_groups"]
    group_of = {}
    group_scope = {}
    for gkey, g in groups.items():
        for wid, scope in g["members"].items():
            # a work in two groups would silently take the LAST group's
            # identity (Codex round-2 HIGH-1)
            if wid in group_of:
                raise GateError(f"work {wid} belongs to two work-groups: "
                                f"{group_of[wid]!r} and {gkey!r}")
            # a blank scope would materialize known_work_member.scope='' -- a
            # witness of no named division (Codex round-6 HIGH-2)
            if not isinstance(scope, str) or not scope.strip():
                raise GateError(f"work-group {gkey!r} member {wid}: blank/invalid "
                                f"scope {scope!r}")
            group_of[wid] = gkey
            group_scope[wid] = scope
    # anthology containers have NO whole-work identity: reject them in every
    # whole-work union source, not just same_work edges (round-4 HIGH-4)
    for gkey, g in groups.items():
        bad = sorted(set(g["members"]) & anth)
        if bad:
            raise GateError(f"work-group {gkey!r} contains anthology "
                            f"container(s) {bad}")

    con.execute("PRAGMA foreign_keys=ON")
    # a work must carry ONE title and ONE author string db-wide -- MIN() must
    # never hide intra-work disagreement (Codex registry review MED-2)
    ragged = con.execute(
        "SELECT work_id, COUNT(DISTINCT COALESCE(work_title,'')), "
        "COUNT(DISTINCT COALESCE(work_author,'')) FROM review_row "
        "GROUP BY work_id HAVING COUNT(DISTINCT COALESCE(work_title,'')) > 1 "
        "OR COUNT(DISTINCT COALESCE(work_author,'')) > 1").fetchall()
    if ragged:
        raise GateError(f"{len(ragged)} works carry mixed title/author strings: "
                        f"{ragged[:10]}")
    meta = {}
    for wid, t, a, c, n in con.execute(
            "SELECT work_id, MIN(work_title), MIN(work_author), MIN(source_corpus), "
            "COUNT(*) FROM review_row GROUP BY work_id"):
        meta[wid] = dict(title=t, author=a or "", corpus=c, rows=n)
    links = con.execute(
        "SELECT rs_work, base_work, kind FROM work_alias_fact").fetchall()

    # the alias-fact table is mutable; it must match the state the step-0
    # inputs were generated against (Codex registry review MED-3)
    alias_ser = json.dumps(sorted((r, b, k) for r, b, k in links),
                           ensure_ascii=False).encode("utf-8")
    got_alias = hashlib.sha256(alias_ser).hexdigest()
    if got_alias != fams["alias_fact_sha256"]:
        raise GateError(f"work_alias_fact drifted since step-0 generation: "
                        f"pinned {fams['alias_fact_sha256'][:12]}.. got {got_alias[:12]}.. "
                        f"({len(links)} rows vs pinned {fams['alias_fact_count']}) "
                        "-- re-run build_inputs.py")

    def resolve_author(wid):
        """Authority-resolved author for a member work (MED-5: the pinned
        authority input is THE source; review_row is only its raw material)."""
        if wid in author_rulings:
            return author_rulings[wid], "owner_ruling"
        raw = meta[wid]["author"]
        if raw:
            return variants.get(raw, raw), "authority"
        if wid in fills:
            return fills[wid]["author"], "authority"
        return None, "none"

    def resolve_title(wid):
        return title_rulings.get(wid, meta[wid]["title"])

    # ---- witness clusters (whole-work identity) ------------------------------
    uf = UnionFind()
    for wid in meta:
        if wid not in anth:
            uf.find(wid)
    census_canonical = {}
    for g in census["merges"]:
        present = [m for m in g["members"] if m in meta]
        for m in present:
            census_canonical.setdefault(g["canonical"], g["canonical"])
        for a, b in zip(present, present[1:]):
            uf.union(a, b)
    canonical_ids = {g["canonical"] for g in census["merges"]}

    # owner-added whole-work merges (round-8 HIGH: three Rabenu Hananel pairs
    # the upstream census leaves split). They are a SEPARATE mechanism: an id
    # may be claimed by the upstream contract or by an owner ruling, never both.
    upstream_members = {m for g in census["merges"] for m in g["members"]}
    owner_members, owner_canonical_ids = {}, set()
    for g in census.get("owner_merges", []):
        for m in g["members"]:
            if m not in meta:
                raise GateError(f"owner merge member {m} has no evidence rows")
            if m in anth:
                raise GateError(f"owner merge {g['members']} contains anthology "
                                f"container {m}")
            if m in upstream_members:
                raise GateError(f"owner merge member {m} is already claimed by "
                                "an upstream census merge")
            if m in owner_members:
                raise GateError(f"owner merge member {m} is claimed by two owner "
                                f"merges: {owner_members[m]} / {g['members']}")
            owner_members[m] = g["members"]
        owner_canonical_ids.add(g["canonical"])
        for a, b in zip(g["members"], g["members"][1:]):
            uf.union(a, b)
    for rs, bw, kind in links:
        if kind != "same_work":
            continue
        if rs in anth or bw in anth:
            raise GateError(f"same_work edge touches an anthology container: {rs}-{bw}")
        uf.union(rs, bw)
    for gkey, g in groups.items():
        mems = [m for m in g["members"] if m in meta]
        for a, b in zip(mems, mems[1:]):
            uf.union(a, b)

    clusters = defaultdict(list)
    for wid in meta:
        if wid not in anth:
            clusters[uf.find(wid)].append(wid)

    # contained parts of container_is_work families; two co-witness containers
    # of the SAME family may share parts, two DIFFERENT families may not
    # (round-4 HIGH-2), and a part may not itself be an anthology container
    part_family = {}
    for cid, f in ciw.items():
        for p in f["contains_parts"]:
            if p in anth:
                raise GateError(f"family part {p} of {f['family']!r} is itself "
                                "an anthology container")
            prev = part_family.get(p)
            if prev is not None and prev != f["family"]:
                raise GateError(f"part {p} claimed by two families: "
                                f"{prev!r} / {f['family']!r}")
            part_family[p] = f["family"]

    # ---- resolve each cluster to a known work --------------------------------
    kws = {}      # anchor -> dict(title, author_pool, basis)
    members = []  # (anchor, work_id, scope, scope_prefix, basis, rows)

    # census reconciliation must be EXACT: every db-absent census member must
    # be pinned as non-materialized, and nothing else (Codex review MED-4)
    live_absent = {m for g in census["merges"] for m in g["members"] if m not in meta}
    if live_absent != set(census["non_materialized_members"]):
        raise GateError(f"census absent-member reconciliation failed: db-absent "
                        f"{sorted(live_absent)} vs pinned "
                        f"{sorted(census['non_materialized_members'])}")

    # referential validity of the pinned inputs (Codex round-2 MED-3)
    for g in census["merges"]:
        if g["canonical"] not in g["members"]:
            raise GateError(f"census canonical {g['canonical']} is not a member "
                            f"of its own merge group {g['members']}")
        bad = sorted(set(g["members"]) & anth)
        if bad:
            raise GateError(f"census merge {g['members']} contains anthology "
                            f"container(s) {bad}")
    # ONLY an anthology container routes its rows by scope; a scope entry for a
    # non-anthology work would give it a second membership and count its rows
    # twice (Codex round-6 HIGH-1). Equality also forces every anthology
    # container to declare its routing.
    if set(scope_map["containers"]) != anth:
        raise GateError(
            f"scope-map containers must be exactly the anthology set: "
            f"scoped-not-anthology {sorted(set(scope_map['containers']) - anth)}, "
            f"anthology-not-scoped {sorted(anth - set(scope_map['containers']))}")
    for cid in scope_map["containers"]:
        if cid not in meta:
            raise GateError(f"scope-map container {cid} does not exist in the db")
    for e in fams["shares_material_edges"]:
        for end in (e["a"], e["b"]):
            if end not in meta:
                raise GateError(f"shares_material edge endpoint {end} does not "
                                "exist in the db")
    # ... and of the alias facts and group members (round-3 MED)
    for r, b, k in links:
        if r not in meta or b not in meta:
            raise GateError(f"work_alias_fact edge {r}->{b} ({k}) has an "
                            "endpoint with no evidence rows")
    for gkey, g in groups.items():
        for m in g["members"]:
            if m not in meta:
                raise GateError(f"work-group {gkey!r} member {m} does not "
                                "exist in the db")

    # family/containment closure (round-3 HIGH-2): the declared family lists
    # and the live containment facts must coincide EXACTLY, in both directions
    live_contains = defaultdict(set)
    live_partners = defaultdict(set)
    for r, b, k in links:
        # an unknown kind used to be silently filed as a same_work partner while
        # the identity union ignored it -- the "partner" then landed in a
        # DIFFERENT known work and closure still passed (Codex round-6 HIGH-3)
        if k == "same_work_contains":
            live_contains[r].add(b)
        elif k == "same_work":
            live_partners[r].add(b)
        else:
            raise GateError(f"work_alias_fact {r}->{b}: unsupported kind {k!r} "
                            "(expected same_work / same_work_contains)")
    for cid, f in families.items():
        if cid not in meta:
            raise GateError(f"family container {cid} ({f['family']!r}) does "
                            "not exist in the db")
        if set(f["contains_parts"]) != live_contains.get(cid, set()):
            raise GateError(
                f"family {f['family']!r}: pinned contains_parts "
                f"{sorted(f['contains_parts'])} != live containment facts "
                f"{sorted(live_contains.get(cid, set()))}")
        if set(f["same_work_partners"]) != live_partners.get(cid, set()):
            raise GateError(
                f"family {f['family']!r}: pinned same_work_partners "
                f"{sorted(f['same_work_partners'])} != live same_work facts "
                f"{sorted(live_partners.get(cid, set()))}")
    undeclared = set(live_contains) - set(families)
    if undeclared:
        raise GateError(f"containers with containment facts but no family "
                        f"declaration: {sorted(undeclared)}")

    def ensure_kw(anchor, title, basis):
        # every known work is titled at exactly this point, from four sources
        # (family key, group key, resolved work title, mint): none may be blank
        # (Codex round-7 HIGH-1)
        if not isinstance(title, str) or not title.strip():
            raise GateError(f"known work {anchor!r} ({basis}) has a blank title "
                            f"{title!r}")
        if anchor not in kws:
            kws[anchor] = dict(title=title, basis=basis, authors=Counter(),
                               ruled=set())
        return anchor

    for root, mems in sorted(clusters.items()):
        mems = sorted(mems)
        fam_keys = sorted({ciw[m]["family"] for m in mems if m in ciw})
        part_fams = sorted({part_family[m] for m in mems if m in part_family})
        gkeys = sorted({group_of[m] for m in mems if m in group_of})
        canons = sorted(m for m in mems if m in canonical_ids)
        ocanons = sorted(m for m in mems if m in owner_canonical_ids)
        omems = sorted(m for m in mems if m in owner_members)
        # an owner merge asserts a whole-work identity of its own: it may not be
        # absorbed by a family/group branch, nor united with a census canonical
        # or a second owner merge, without a fresh ruling
        if omems and (fam_keys or part_fams or gkeys):
            raise GateError(f"owner-merged {omems} pulled into a family/group "
                            f"cluster {mems}: {fam_keys} {part_fams} {gkeys}")
        if omems and canons:
            raise GateError(f"owner merge {omems} united with census canonical(s) "
                            f"{canons} in cluster {mems} -- needs an owner ruling")
        if len(ocanons) > 1:
            raise GateError(f"cluster {mems} merges two owner merges {ocanons} "
                            "-- needs an owner ruling")

        if len(fam_keys) > 1 or len(part_fams) > 1 or len(gkeys) > 1:
            raise GateError(f"cluster {mems} spans families/groups: "
                            f"{fam_keys} {part_fams} {gkeys}")
        # the three identity categories are mutually exclusive per cluster
        # (Codex registry review HIGH-1a: part+group used to slip through green)
        if sum(map(bool, (fam_keys, part_fams, gkeys))) > 1:
            raise GateError(f"cluster {mems} mixes identity categories: "
                            f"containers={fam_keys} parts={part_fams} groups={gkeys}")
        # an owner work-group overrides the census ONLY for its own named
        # members (HIGH-1b: an external canonical merged in must still fail)
        # `is True`: only an explicit boolean true authorizes the override
        override_ok = (gkeys and groups[gkeys[0]].get("overrides_census") is True
                       and set(canons) <= set(groups[gkeys[0]]["members"]))
        if len(canons) > 1 and not override_ok:
            raise GateError(f"cluster {mems} merges two census canonicals {canons} "
                            "-- a new identity assertion; needs an owner ruling")

        if fam_keys:
            anchor = ensure_kw("family:" + fam_keys[0], fam_keys[0], "family")
            for m in mems:
                scope = "whole" if m in ciw else (group_scope.get(m) or "whole")
                basis = "family_container" if m in ciw else "same_work_link"
                members.append((anchor, m, scope, None, basis, None, meta[m]["rows"]))
        elif part_fams:
            anchor = ensure_kw("family:" + part_fams[0], part_fams[0], "family")
            for m in mems:
                scope = resolve_title(m)  # the part's own title names its division
                members.append((anchor, m, scope, None, "family_part", None,
                                meta[m]["rows"]))
        elif gkeys:
            anchor = ensure_kw("group:" + gkeys[0], gkeys[0], "work_group")
            for m in mems:
                members.append((anchor, m, group_scope.get(m, "whole"), None,
                                "work_group", None, meta[m]["rows"]))
        elif len(mems) == 1:
            m = mems[0]
            anchor = ensure_kw("work:" + m, resolve_title(m), "singleton")
            members.append((anchor, m, "whole", None, "singleton", None,
                            meta[m]["rows"]))
        else:
            if canons:
                head, basis, b = canons[0], "census_canonical", "census"
            elif ocanons:
                head, basis, b = ocanons[0], "owner_merge", "owner_merge"
            else:
                head, basis, b = mems[0], "cluster", "same_work_link"
            anchor = ensure_kw("work:" + head, resolve_title(head), basis)
            for m in mems:
                members.append((anchor, m, "whole", None, b, None, meta[m]["rows"]))
        for m in mems:
            a, basis = resolve_author(m)
            if basis == "owner_ruling":
                kws[anchor]["ruled"].add(a)
            if a:
                kws[anchor]["authors"][a] += meta[m]["rows"]

    # ---- scoped attachments from the scope map -------------------------------
    # target work -> its cluster anchor
    anchor_of_work = {}
    for anchor, wid, *_ in members:
        anchor_of_work.setdefault(wid, anchor)

    contains = {(r, b) for r, b, k in links if k == "same_work_contains"}
    routed_rows = defaultdict(int)
    provisional = set()  # minted kws whose identification is deliberately open
    for cid, entries in scope_map["containers"].items():
        # entry shape is validated BEFORE any routing: an empty prefix matches
        # every label (and a NULL label), 'whole' would mint a whole-scope
        # witness out of a routed part, and a duplicate prefix double-counts
        # rows (Codex round-5 HIGH-2)
        seen_prefixes = set()
        for e in entries:
            p = e.get("prefix")
            if not isinstance(p, str) or not p.strip():
                raise GateError(f"scope entry {cid}: empty/invalid prefix {p!r}")
            if p == "whole":
                raise GateError(f"scope entry {cid}: prefix 'whole' -- a routed "
                                "part may never claim the whole-work scope")
            if p in seen_prefixes:
                raise GateError(f"scope entry {cid}: duplicate prefix {p!r}")
            seen_prefixes.add(p)
            # exactly ONE non-empty target key: {'work','mint'} silently took
            # the work branch, and {'mint': ''} minted a titleless known work
            # (Codex round-5 HIGH-1)
            t = e.get("target")
            if not isinstance(t, dict):
                raise GateError(f"scope entry {cid} prefix {p!r}: target is not "
                                f"an object: {t!r}")
            bad_keys = set(t) - {"work", "group", "mint"}
            if bad_keys:
                raise GateError(f"scope entry {cid} prefix {p!r}: unknown target "
                                f"key(s) {sorted(bad_keys)}")
            if len(t) != 1:
                raise GateError(f"scope entry {cid} prefix {p!r}: target must "
                                f"name exactly one of work/group/mint, got "
                                f"{sorted(t)}")
            tv = next(iter(t.values()))
            if not isinstance(tv, str) or not tv.strip():
                raise GateError(f"scope entry {cid} prefix {p!r}: empty target "
                                f"value {tv!r}")
            # route provenance must be possible for the target type: only an
            # existing work/group can carry a verified containment edge, and
            # only a mint can be left provisionally open for the owner
            # (Codex round-6 HIGH-4)
            b = e.get("basis")
            if b not in ("verified_link", "division_title", "pending_owner"):
                raise GateError(f"scope entry {cid} prefix {p!r}: unknown basis "
                                f"{b!r}")
            tkey = next(iter(t))
            if b == "verified_link" and tkey not in ("work", "group"):
                raise GateError(f"scope entry {cid} prefix {p!r}: basis "
                                f"verified_link cannot target a {tkey}")
            if b == "pending_owner" and tkey != "mint":
                raise GateError(f"scope entry {cid} prefix {p!r}: basis "
                                f"pending_owner must target a mint, not a {tkey}")
        prefixes = sorted((e["prefix"] for e in entries), key=len, reverse=True)
        counts = defaultdict(int)
        for label, n in con.execute(
                "SELECT locus_label, COUNT(*) FROM review_row WHERE work_id=? "
                "GROUP BY locus_label", (cid,)):
            if not label:
                raise GateError(f"unroutable rows in {cid}: {n} rows carry no "
                                "locus_label")
            hit = next((p for p in prefixes if label.startswith(p)), None)
            if hit is None:
                raise GateError(f"unrouted rows in {cid}: label {label!r} ({n} rows)")
            counts[hit] += n
        for e in entries:
            # a scope entry must route a positive number of rows, and exactly
            # the number pinned at generation time (round-3 HIGH-1: a dead
            # prefix minted a phantom member; a prefix shadowing another
            # silently moved rows)
            n_routed = counts.get(e["prefix"], 0)
            if n_routed <= 0 or n_routed != e["rows_matched"]:
                raise GateError(
                    f"scope entry {cid} prefix {e['prefix']!r}: routed "
                    f"{n_routed} rows, pinned rows_matched={e['rows_matched']}")
            t = e["target"]
            if "work" in t:
                tid = t["work"]
                # pinned target-title assertion: a mis-keyed id behind a
                # right-looking prefix must fail (Codex review MED-6)
                if tid not in meta or resolve_title(tid) != e.get("target_title"):
                    raise GateError(
                        f"scope target {tid}: pinned title {e.get('target_title')!r}"
                        f" != db title {resolve_title(tid) if tid in meta else None!r}")
                if e["basis"] == "verified_link" and (cid, tid) not in contains:
                    raise GateError(f"scope entry {cid}->{tid} claims verified_link "
                                    "but no containment edge exists")
                if tid not in anchor_of_work:
                    raise GateError(f"scope target {tid} has no known work")
                anchor = anchor_of_work[tid]
            elif "group" in t:
                gk = t["group"]
                anchor = "group:" + gk
                if anchor not in kws:
                    raise GateError(f"scope target group {gk!r} unknown")
                if e["basis"] == "verified_link" and not any(
                        (cid, m) in contains for m in groups[gk]["members"]):
                    raise GateError(f"scope entry {cid}->group {gk!r} claims "
                                    "verified_link but no member has a containment edge")
            elif "mint" in t:
                anchor = ensure_kw("mint:" + t["mint"], t["mint"], "mint")
                if e["basis"] == "pending_owner":
                    provisional.add(anchor)
            else:  # unreachable: the entry-shape gate above allows no other key
                raise GateError(f"scope entry {cid}: unhandled target {t!r}")
            members.append((anchor, cid, e["prefix"], e["prefix"], "scope_map",
                            e["basis"], counts.get(e["prefix"], 0)))
            routed_rows[cid] += counts.get(e["prefix"], 0)

    # anthology containers must be fully routed
    for cid in sorted(set(scope_map["containers"]) & set(meta)):
        if routed_rows[cid] != meta[cid]["rows"]:
            raise GateError(f"{cid}: routed {routed_rows[cid]} of {meta[cid]['rows']} rows")

    # ---- gates ----------------------------------------------------------------
    check_membership_gates(members, meta)

    # ---- author resolution (from the pinned authority input, MED-5) ----------
    author_conflicts = []
    kw_author, kw_author_basis = {}, {}
    for anchor, k in kws.items():
        plain = {a for a in k["authors"] if "תרגום" not in a and ";" not in a}
        ruled = k["ruled"]
        if len(ruled) > 1:
            author_conflicts.append((anchor, k["title"], sorted(map(str, ruled))))
            continue
        if ruled:
            rv = next(iter(ruled))
            if plain - ({rv} if rv else set()):
                author_conflicts.append(
                    (anchor, k["title"], [f"ruled={rv}"] + sorted(plain)))
                continue
            kw_author[anchor], kw_author_basis[anchor] = rv, "owner_ruling"
        elif len(plain) > 1:
            author_conflicts.append((anchor, k["title"], sorted(k["authors"])))
        else:
            a = (sorted(plain)[0] if plain else
                 (k["authors"].most_common(1)[0][0] if k["authors"] else None))
            kw_author[anchor] = a
            kw_author_basis[anchor] = "authority" if a else "none"
    if author_conflicts:
        for a, t, s in author_conflicts[:20]:
            say(f"AUTHOR CONFLICT {a} {t}: {s}")
        raise GateError(f"{len(author_conflicts)} known works with conflicting authors")

    # ---- main witness: citable loci desc, evidence rows desc, work_id asc ----
    has_locus = dict(con.execute(
        "SELECT work_id, MAX(CASE WHEN locus_label IS NOT NULL THEN 1 ELSE 0 END) "
        "FROM review_row GROUP BY work_id"))
    # whole-scope first (a scoped part cannot cite the whole work), then
    # citable loci, then evidence rows, then lowest id; stored at the member
    # grain (work_id, scope) so step 2 gets one unambiguous locus scheme
    cands = defaultdict(list)
    for anchor, wid, scope, prefix, basis, rbasis, rows in members:
        cands[anchor].append((0 if scope == "whole" else 1,
                              -has_locus.get(wid, 0), -rows, wid, scope))
    best = {a: (sorted(c)[0][3], sorted(c)[0][4]) for a, c in cands.items()}

    # ---- write ---------------------------------------------------------------
    try:
        con.execute("BEGIN")
        # The CARD grain (scripts/attach_review_cards.py) is projected FROM this
        # registry and references known_work, so it is dropped here for two
        # reasons: FKs are ON, and cards built against the previous identities
        # would otherwise survive a rebuild that changed them. Its meta rows go
        # with it, so nothing claims a projection that no longer exists -- the
        # viewer then hides card mode until the attach script runs again.
        dropped_cards = bool(con.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='card'"
        ).fetchone())
        # children before parents: FKs are ON
        for t in ("card_member", "card", "known_work_member",
                  "known_work_assertion", "work_relation", "known_work"):
            con.execute(f"DROP TABLE IF EXISTS {t}")
        con.execute("DELETE FROM meta WHERE key LIKE 'card_grain.%'")
        for ddl in DDL:
            con.execute(ddl)
        for anchor in sorted(kws):
            k = kws[anchor]
            con.execute(
                "INSERT INTO known_work VALUES (?,?,?,?,?,?,?,?,?,?)",
                (kw_id_of(anchor), anchor, k["title"], kw_author[anchor],
                 kw_author_basis[anchor], k["basis"],
                 1 if anchor in provisional else 0,
                 best[anchor][0], best[anchor][1], "default"))
        con.executemany(
            "INSERT INTO known_work_member VALUES (?,?,?,?,?,?,?)",
            [(kw_id_of(a), w, s, p, b, rb, r)
             for a, w, s, p, b, rb, r in members])
        for nm in sorted(census["non_materialized_members"]):
            # an absent member may appear in several merges only if every
            # candidate canonical resolves to ONE known work (round-4 HIGH-3)
            anchors = set()
            for g in census["merges"]:
                if nm not in g["members"]:
                    continue
                can = g["canonical"]
                if can == nm or can not in anchor_of_work:
                    raise GateError(f"non-materialized member {nm}: canonical "
                                    f"{can} has no materialized known work")
                anchors.add(anchor_of_work[can])
            if len(anchors) != 1:
                raise GateError(f"non-materialized member {nm} asserts to "
                                f"{len(anchors)} known works: {sorted(anchors)}")
            con.execute(
                "INSERT INTO known_work_assertion VALUES (?,?,?)",
                (kw_id_of(anchors.pop()), nm,
                 "census member with no evidence rows (MED-3)"))
        con.executemany(
            "INSERT OR IGNORE INTO work_relation VALUES (?,?,'shares_material',?)",
            [(e["a"], e["b"], e["note"]) for e in fams["shares_material_edges"]])
        for k, v in (("work_registry.version", "2"),
                     ("work_registry.pins_sha256", pins_hash),
                     ("work_registry.pins_root_verified",
                      "yes" if pins_sha256 else "no"),
                     ("work_registry.alias_fact_sha256", got_alias),
                     ("work_registry.known_works", str(len(kws))),
                     ("work_registry.members", str(len(members))),
                     ("doc.work_registry", DOC)):
            con.execute("INSERT OR REPLACE INTO meta VALUES (?,?)", (k, v))
        con.execute("COMMIT")
    except Exception:
        try:
            con.execute("ROLLBACK")
        except sqlite3.Error:
            pass
        raise  # build() closes the connection in its finally
    n_bases = Counter(k["basis"] for k in kws.values())
    if dropped_cards:
        say("the card grain was dropped (it projects these identities) -- "
            "re-run scripts/attach_review_cards.py")
    say(f"known works: {len(kws)} ({dict(n_bases)}); members: {len(members)}; "
        f"relations: {len(fams['shares_material_edges'])}")
    say(f"trusted root (PINS.json sha256): {pins_hash}")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default=os.path.join(
        REPO_ROOT, "discovery_data", "discovery-v5-REVIEW.db"))
    ap.add_argument("--inputs-dir", default=DEFAULT_INPUTS)
    ap.add_argument("--pins-sha256", required=True,
                    help="trusted root: expected sha256 of PINS.json itself, "
                         "carried by the OPERATOR (printed by build_inputs.py), "
                         "never read from the inputs directory")
    args = ap.parse_args(argv)
    if not os.path.exists(args.db):
        raise SystemExit("missing: %s" % args.db)
    build(args.db, args.inputs_dir, pins_sha256=args.pins_sha256)
    return 0


if __name__ == "__main__":
    sys.exit(main())
