#Requires -Version 5.1
<#
.SYNOPSIS
    Register the nightly review-artifact verification as a Windows scheduled task.

.DESCRIPTION
    Context (2026-09-09). The offset verifier's mutation tests used to run against
    the real 3.45 GB / 519,382-row review DB on every test run: 3,396 seconds,
    66.5% of the whole non-GUI suite, paid only on this machine because CI has no
    review DB and skipped the file for free.

    Those mutation tests now run against a synthetic fixture in about a second.
    That change removes 57 minutes from every run, but it also removes the
    incidental full-artifact check that came with it -- and a check that used to
    happen every run must not become a check that happens never.

    This registers the replacement cadence: scripts/verify_review_artifact.py,
    nightly, on the one machine that holds the data. That script FAILS (exit 2)
    when the DB, source keys or corpus file are absent rather than skipping, so a
    missing-data night is visible instead of silently green, and it appends one
    JSON record per run (commit, DB identity, row count, duration, verdict) to
    _tmp/artifact-verify-log.jsonl.

    A nightly green certifies the artifact it ran against, NOT a newly built one.
    Before promoting a rebuilt DB, run the script directly with --expect-rows.

.PARAMETER Time
    Local time to run, HH:mm. Default 03:00.

.PARAMETER TaskName
    Scheduled-task name. Default GenizahSearch-VerifyReviewArtifact.

.PARAMETER WhatIfOnly
    Print the task definition and exit without registering anything.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\schedule_nightly_artifact_verify.ps1 -WhatIfOnly
    powershell -ExecutionPolicy Bypass -File scripts\schedule_nightly_artifact_verify.ps1
#>
param(
    [string]$Time = "03:00",
    [string]$TaskName = "GenizahSearch-VerifyReviewArtifact",
    [switch]$WhatIfOnly
)

$ErrorActionPreference = "Stop"

$repo = Split-Path -Parent $PSScriptRoot
$script = Join-Path $repo "scripts\verify_review_artifact.py"
$logDir = Join-Path $repo "_tmp"
$jsonLog = Join-Path $logDir "artifact-verify-log.jsonl"
$textLog = Join-Path $logDir "artifact-verify-last.txt"

if (-not (Test-Path $script)) {
    throw "not found: $script"
}

$python = (Get-Command python -ErrorAction SilentlyContinue)
if ($null -eq $python) { throw "python is not on PATH" }
$pythonPath = $python.Source

# The command goes into a generated .cmd file rather than into the task's
# Argument string, and this is not a style choice -- the first version of this
# script hand-built `/c ""python.exe" -X utf8 -u "script.py" --json-out
# "log.jsonl"" > "last.txt" 2>&1` and it DID NOT RUN. cmd.exe strips the outer
# quotes after /c only under conditions that a command containing several
# quoted paths does not meet, so it took the other branch, failed to parse,
# exited 1, and never even created the redirect target -- no console log, no
# jsonl line, nothing to notice except an exit code no one was reading.
#
# It looked fine when tested through PowerShell, because Start-Process
# re-quotes -ArgumentList and happened to fix it. Task Scheduler passes the
# string verbatim, so the two disagreed. A wrapper file removes the quoting
# question entirely: the task runs `cmd.exe /c "<one path>"`, which cmd does
# handle, and the .cmd itself is plain readable lines you can run by hand.
#
# -u so the log is written as it goes rather than on exit; the text log keeps
# the LAST run's full output while the jsonl keeps every run's verdict.
$wrapper = Join-Path $PSScriptRoot "nightly_verify_review_artifact.cmd"
$wrapperBody = @"
@echo off
REM GENERATED by scripts/schedule_nightly_artifact_verify.ps1 -- do not edit.
REM Run by the scheduled task '$TaskName'. Safe to run by hand.
cd /d "$repo"
"$pythonPath" -X utf8 -u "$script" --json-out "$jsonLog" > "$textLog" 2>&1
exit /b %ERRORLEVEL%
"@
$wrapped = ('/c "{0}"' -f $wrapper)

Write-Output "repo        : $repo"
Write-Output "task        : $TaskName"
Write-Output "time        : $Time (daily)"
Write-Output "python      : $pythonPath"
Write-Output "json log    : $jsonLog"
Write-Output "text log    : $textLog"
Write-Output ""
Write-Output "wrapper     : $wrapper"
Write-Output "command     : cmd.exe $wrapped"
Write-Output ""
Write-Output "--- wrapper contents ---"
Write-Output $wrapperBody
Write-Output "------------------------"
Write-Output ""

if ($WhatIfOnly) {
    Write-Output "-WhatIfOnly given: nothing registered, no wrapper written."
    exit 0
}

if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir | Out-Null }

$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($null -ne $existing) {
    Write-Output "A task named '$TaskName' already exists. Not overwriting it."
    Write-Output "Remove it first if you mean to replace it:"
    Write-Output "  Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
    exit 1
}

# ASCII, no BOM: cmd.exe mis-reads a UTF-8 BOM as part of the first command.
[System.IO.File]::WriteAllText(
    $wrapper, ($wrapperBody -replace "`r?`n", "`r`n"),
    (New-Object System.Text.ASCIIEncoding))
Write-Output "wrote $wrapper"

$action = New-ScheduledTaskAction -Execute "cmd.exe" -Argument $wrapped -WorkingDirectory $repo
$trigger = New-ScheduledTaskTrigger -Daily -At $Time
# Deliberately NOT WakeToRun and NOT RunOnlyIfNetworkAvailable: the check is
# entirely local, and a machine that was asleep should show a MISSED night
# rather than be woken for it.
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable `
    -DontStopIfGoingOnBatteries -AllowStartIfOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2)

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings -Description ("Nightly full verification of " +
    "discovery-v5-REVIEW.db offsets. Fails on missing data rather than " +
    "skipping. See scripts/verify_review_artifact.py.") | Out-Null

Write-Output "Registered."
Write-Output ""

# PROVE IT CAN RUN. "Registered" is not "works": the first version of this
# script registered a task that exited 1 without executing anything, and
# nothing would have revealed that until someone thought to read a log that
# was never created. So the task is started here and watched until it has
# actually produced output. This is a plumbing check, not the full 15-minute
# verification -- once the console log has content, cmd found python, python
# found the script, and the redirect works, which is everything the wrapper
# is responsible for. The nightly run does the rest.
if (Test-Path $textLog) { Remove-Item $textLog -Force }
Write-Output "Starting it once to prove the plumbing (not the full run)..."
Start-ScheduledTask -TaskName $TaskName

$deadline = [DateTime]::UtcNow.AddSeconds(90)
$sawOutput = $false
while ([DateTime]::UtcNow -lt $deadline) {
    Start-Sleep -Seconds 3
    if ((Test-Path $textLog) -and (Get-Item $textLog).Length -gt 0) {
        $sawOutput = $true
        break
    }
    $state = (Get-ScheduledTask -TaskName $TaskName).State
    if ($state -ne "Running") {
        $rc = (Get-ScheduledTaskInfo -TaskName $TaskName).LastTaskResult
        Write-Output ""
        Write-Output "PROBLEM: the task stopped (exit $rc) without writing any"
        Write-Output "output to $textLog."
        Write-Output "The schedule exists but does NOT work. Run the wrapper by"
        Write-Output "hand to see why:"
        Write-Output "  cmd /c `"$wrapper`""
        exit 1
    }
}

if (-not $sawOutput) {
    Write-Output ""
    Write-Output "PROBLEM: 90s in, the task is still running but has written"
    Write-Output "nothing to $textLog. Check it by hand before trusting it."
    exit 1
}

Write-Output "Plumbing OK -- the task is running and writing to:"
Write-Output "  $textLog"
Get-Content $textLog -Tail 5 | ForEach-Object { "    $_" }
Write-Output ""
Write-Output "It will keep going for roughly 15 minutes. Stop this test run with:"
Write-Output "  Stop-ScheduledTask -TaskName '$TaskName'"
Write-Output "or leave it -- either way the real run is nightly at $Time."
Write-Output ""
Write-Output "A failed or missed night must stay visible -- check $jsonLog"
Write-Output "and treat a gap in its dates as an unverified artifact."
