#Requires -Version 5.1
<#
.SYNOPSIS
    Register the nightly real-index check of search combinations as a Windows
    scheduled task.

.DESCRIPTION
    Context (2026-10-04, owner decision D8). The desktop keeps a 50,000-candidate
    cut-off for what it shows and completes a cut-off step only when search-within
    or the all-terms filter relies on it. Whether that combination misses nothing
    can only be checked against the real index -- minutes of uncapped searches --
    so it is not a test: scripts/verify_search_combinations.py runs it, nightly,
    on the machine that holds the index.

    That script FAILS (exit 2) when the index, the browse map or libraries.csv is
    absent rather than skipping, and FAILS (exit 1) when its check would be
    vacuous (the parent word no longer reaches the limit). It appends one JSON
    record per run (commit, counts, verdict) to _tmp/search-gate-log.jsonl.

    This copies the wrapper and the plumbing proof of
    scripts/schedule_nightly_artifact_verify.ps1 -- read the comments there for
    why the command is a generated .cmd and why the task is started once here.

.PARAMETER Time
    Local time to run, HH:mm. Default 04:30 (the review-artifact check starts at
    03:00 and runs about an hour; both hold gigabytes).

.PARAMETER TaskName
    Scheduled-task name. Default GenizahSearch-VerifySearchCombinations.

.PARAMETER WhatIfOnly
    Print the task definition and exit without registering anything.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts\schedule_nightly_search_gate.ps1 -WhatIfOnly
    powershell -ExecutionPolicy Bypass -File scripts\schedule_nightly_search_gate.ps1
#>
param(
    [string]$Time = "04:30",
    [string]$TaskName = "GenizahSearch-VerifySearchCombinations",
    [switch]$WhatIfOnly
)

$ErrorActionPreference = "Stop"

$repo = Split-Path -Parent $PSScriptRoot
$script = Join-Path $repo "scripts\verify_search_combinations.py"
$logDir = Join-Path $repo "_tmp"
$jsonLog = Join-Path $logDir "search-gate-log.jsonl"
$textLog = Join-Path $logDir "search-gate-last.txt"

if (-not (Test-Path $script)) {
    throw "not found: $script"
}

$python = (Get-Command python -ErrorAction SilentlyContinue)
if ($null -eq $python) { throw "python is not on PATH" }
$pythonPath = $python.Source

# A generated .cmd wrapper, not a hand-quoted Argument string: Task Scheduler passes
# that string verbatim and cmd.exe mis-parses several quoted paths after /c (see
# scripts/schedule_nightly_artifact_verify.ps1, where the first version did not run).
$wrapper = Join-Path $PSScriptRoot "nightly_verify_search_combinations.cmd"
$wrapperBody = @"
@echo off
REM GENERATED by scripts/schedule_nightly_search_gate.ps1 -- do not edit.
REM Run by the scheduled task '$TaskName'. Safe to run by hand.
cd /d "$repo"
"$pythonPath" -X utf8 -u "$script" --json-out "$jsonLog" > "$textLog" 2>&1
exit /b %ERRORLEVEL%
"@
$wrapped = ('/c "{0}"' -f $wrapper)

Write-Output "repo        : $repo"
Write-Output "task        : $TaskName"
Write-Output "time        : $Time (daily)"
Write-Output "python      : $pythonPath"
Write-Output "json log    : $jsonLog"
Write-Output "text log    : $textLog"
Write-Output ""
Write-Output "wrapper     : $wrapper"
Write-Output "command     : cmd.exe $wrapped"
Write-Output ""
Write-Output "--- wrapper contents ---"
Write-Output $wrapperBody
Write-Output "------------------------"
Write-Output ""

if ($WhatIfOnly) {
    Write-Output "-WhatIfOnly given: nothing registered, no wrapper written."
    exit 0
}

if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir | Out-Null }

$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($null -ne $existing) {
    Write-Output "A task named '$TaskName' already exists. Not overwriting it."
    Write-Output "Remove it first if you mean to replace it:"
    Write-Output "  Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
    exit 1
}

# ASCII, no BOM: cmd.exe mis-reads a UTF-8 BOM as part of the first command.
[System.IO.File]::WriteAllText(
    $wrapper, ($wrapperBody -replace "`r?`n", "`r`n"),
    (New-Object System.Text.ASCIIEncoding))
Write-Output "wrote $wrapper"

$action = New-ScheduledTaskAction -Execute "cmd.exe" -Argument $wrapped -WorkingDirectory $repo
$trigger = New-ScheduledTaskTrigger -Daily -At $Time
# Deliberately NOT WakeToRun and NOT RunOnlyIfNetworkAvailable: the check is
# entirely local, and a machine that was asleep should show a MISSED night
# rather than be woken for it.
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable `
    -DontStopIfGoingOnBatteries -AllowStartIfOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2)

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings -Description ("Nightly real-index check that search " +
    "combinations miss nothing. Fails on missing data rather than " +
    "skipping. See scripts/verify_search_combinations.py.") | Out-Null

Write-Output "Registered."
Write-Output ""

# PROVE IT CAN RUN. "Registered" is not "works": the first version of this
# script registered a task that exited 1 without executing anything, and
# nothing would have revealed that until someone thought to read a log that
# was never created. So the task is started here and watched until it has
# actually produced output. This is a plumbing check, not the full 5-minute
# check -- once the console log has content, cmd found python, python
# found the script, and the redirect works, which is everything the wrapper
# is responsible for. The nightly run does the rest.
if (Test-Path $textLog) { Remove-Item $textLog -Force }
Write-Output "Starting it once to prove the plumbing (not the full run)..."
Start-ScheduledTask -TaskName $TaskName

$deadline = [DateTime]::UtcNow.AddSeconds(90)
$sawOutput = $false
while ([DateTime]::UtcNow -lt $deadline) {
    Start-Sleep -Seconds 3
    if ((Test-Path $textLog) -and (Get-Item $textLog).Length -gt 0) {
        $sawOutput = $true
        break
    }
    $state = (Get-ScheduledTask -TaskName $TaskName).State
    if ($state -ne "Running") {
        $rc = (Get-ScheduledTaskInfo -TaskName $TaskName).LastTaskResult
        Write-Output ""
        Write-Output "PROBLEM: the task stopped (exit $rc) without writing any"
        Write-Output "output to $textLog."
        Write-Output "The schedule exists but does NOT work. Run the wrapper by"
        Write-Output "hand to see why:"
        Write-Output "  cmd /c `"$wrapper`""
        exit 1
    }
}

if (-not $sawOutput) {
    Write-Output ""
    Write-Output "PROBLEM: 90s in, the task is still running but has written"
    Write-Output "nothing to $textLog. Check it by hand before trusting it."
    exit 1
}

Write-Output "Plumbing OK -- the task is running and writing to:"
Write-Output "  $textLog"
Get-Content $textLog -Tail 5 | ForEach-Object { "    $_" }
Write-Output ""
Write-Output "It will keep going for roughly 5 minutes. Stop this test run with:"
Write-Output "  Stop-ScheduledTask -TaskName '$TaskName'"
Write-Output "or leave it -- either way the real run is nightly at $Time."
Write-Output ""
Write-Output "A failed or missed night must stay visible -- check $jsonLog"
Write-Output "and treat a gap in its dates as an unverified night."
