#!/usr/bin/env python3
"""
Update doc_relation column in documents table from transcriptions_linked.csv

This script populates the doc_relation column to distinguish between:
- Digital Edition (7,664 records) - Original transcriptions (Hebrew/Aramaic)
- Digital Translation (1,696 records) - English translations

Users see "PGP Transcription" only for Digital Editions; translations are filtered out.

Usage:
  python scripts/update_doc_relation.py --dry-run  # Validate and report (default)
  python scripts/update_doc_relation.py --execute  # Actually update data

Prerequisites:
  1. Run migration in Supabase SQL Editor:
     - add_doc_relation_column.sql
  2. Set SUPABASE_SERVICE_KEY environment variable
"""

import argparse
import csv
import io
import os
import sys
from collections import defaultdict
from pathlib import Path

# Load .env file if present
def load_env():
    """Load environment variables from .env file if present."""
    env_path = Path(__file__).parent.parent / '.env'
    if env_path.exists():
        with open(env_path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    # Only set if not already set in environment
                    if key not in os.environ:
                        os.environ[key] = value

load_env()

try:
    from tqdm import tqdm
except ImportError:
    print("ERROR: tqdm not installed. Run: pip install tqdm")
    sys.exit(1)

try:
    from supabase import create_client, Client
except ImportError:
    print("ERROR: supabase not installed. Run: pip install supabase")
    sys.exit(1)

# The verifier lives beside this script. It is what import_pgp_full.py runs before it
# reads transcriptions_linked.csv; this script reads the SAME file and used to run nothing.
sys.path.insert(0, str(Path(__file__).parent))
from fetch_pgp_metadata import PROVENANCE_FILENAME, verify_against_provenance  # noqa: E402

# Constants
BATCH_SIZE = 500  # Match import script pattern
PGP_DATA_DIR = Path(__file__).parent.parent / 'pgp_data'
TRANSCRIPTIONS_CSV = PGP_DATA_DIR / 'transcriptions_linked.csv'
# Read back in chunks this size; PostgREST caps the length of an in() list.
READBACK_CHUNK = 200

# Supabase URL (same as web/supabase_client.py)
SUPABASE_URL = os.environ.get('SUPABASE_URL', 'https://ylcpglwxompwjcufdemz.supabase.co')


def load_doc_relations(csv_path: Path) -> tuple:
    """Path form of load_doc_relations_from_bytes(). main() must not use it: it verifies
    the file's bytes and parses the SAME bytes, so nothing can be swapped in between."""
    with open(csv_path, 'rb') as fh:
        return load_doc_relations_from_bytes(fh.read())


def load_doc_relations_from_bytes(raw: bytes) -> tuple:
    """
    Load pgpid -> doc_relation mapping from transcriptions_linked.csv.

    Returns (relations, skipped): the mapping, and a dict counting every row that
    contributed nothing and why. The file is generated by scripts/pgp_transcriptions_export.py
    and every row it writes carries an integer pgpid and a non-empty doc_relation (measured
    2026-09-22: 10,037 rows, 0 skipped), so a skipped row means the format changed under
    this script -- which used to `continue` silently, until a renamed column classified
    nothing and exited 0.

    An Edition ALWAYS wins over a Translation for the same pgpid. That is not a
    preference, it is the only value consistent with the text actually stored:
    import_pgp_full.py sets documents.transcription from the FIRST 'Digital Edition' row,
    while this used to take the LAST row of any kind. A document with an edition followed
    by a translation therefore held edition text but was labelled a translation -- and
    once doc_relation reaches the sidecar, Browse and Advanced View suppress that text as
    a translation. Measured on the 2026-09-22 corpus: 1,045 documents.

    Returns: Dict mapping pgpid (int) to doc_relation (str)
    """
    relations = {}
    skipped = {'blank_pgpid': 0, 'non_integer_pgpid': 0, 'blank_doc_relation': 0}

    with io.StringIO(raw.decode('utf-8-sig'), newline=None) as f:
        reader = csv.DictReader(f)

        for row in reader:
            # Handle BOM in first column if present
            pgpid_str = row.get('pgpid', '')

            if not pgpid_str:
                skipped['blank_pgpid'] += 1
                continue

            try:
                pgpid = int(pgpid_str)
            except ValueError:
                skipped['non_integer_pgpid'] += 1
                continue

            doc_relation = (row.get('doc_relation') or '').strip()
            if not doc_relation:
                skipped['blank_doc_relation'] += 1
                continue

            # Same predicate the importer uses to pick the transcription
            # (import_pgp_full.py::is_edition_relation); they must not diverge.
            existing = relations.get(pgpid)
            if existing and 'Edition' in existing and 'Edition' not in doc_relation:
                # Already classified by an edition; a later translation must not demote it.
                continue
            relations[pgpid] = doc_relation

    return relations, skipped


def require_verified_inputs(pgp_data_dir: Path, allow_unverified: bool, contents=None) -> None:
    """Refuse to classify from a derived file that does not match its provenance.

    import_pgp_full.py runs this same check before reading transcriptions_linked.csv. This
    script reads the same file for the same refresh and ran nothing -- so the stale or
    hand-edited derived file the importer had just refused was accepted here and its
    doc_relation values pushed to Supabase at exit 0, which is precisely the user-visible
    misclassification the refresh procedure exists to fix.
    """
    problems = verify_against_provenance(str(pgp_data_dir), check_derived=True,
                                         contents=contents)
    if not problems:
        print("  transcriptions_linked.csv verified against %s" % PROVENANCE_FILENAME)
        return
    if allow_unverified:
        print("WARNING: classifying from inputs that do not match %s (--no-provenance-check):"
              % PROVENANCE_FILENAME)
        for problem in problems:
            print("  %s" % problem)
        print()
        return
    print("ERROR: the files in pgp_data/ do not match their provenance:", file=sys.stderr)
    for problem in problems:
        print("  %s" % problem, file=sys.stderr)
    print("", file=sys.stderr)
    print("Re-run:  python scripts/fetch_pgp_metadata.py", file=sys.stderr)
    print("         python scripts/pgp_transcriptions_export.py", file=sys.stderr)
    print("Or pass --no-provenance-check to classify from them anyway.", file=sys.stderr)
    sys.exit(1)


def get_supabase_client() -> Client:
    """Create Supabase client with service role key for writes."""
    service_key = os.getenv('SUPABASE_SERVICE_KEY')

    if not service_key:
        print("ERROR: SUPABASE_SERVICE_KEY environment variable not set")
        print("Note: Service key required for database writes (not anon key)")
        print("Set in .env file or environment")
        sys.exit(1)

    return create_client(SUPABASE_URL, service_key)


def batch_update_doc_relations(client: Client, relations: dict) -> tuple:
    """
    Update doc_relation column in batches.

    Returns: (success_count, not_found_count, failed_count)

    `not found` and `failed` used to be one counter, and the epilogue asserted the benign
    reading of it -- so a Supabase outage that failed thousands of updates printed "this
    is expected for multi-fragment documents" and exited 0. They are different events and
    only one of them is normal, so they are counted separately and only one of them is
    fatal.
    """
    success_count = 0
    not_found_count = 0
    failed_count = 0

    # Convert to list of (pgpid, doc_relation) for batching
    items = list(relations.items())

    for i in tqdm(range(0, len(items), BATCH_SIZE), desc="Updating batches"):
        batch = items[i:i + BATCH_SIZE]

        for pgpid, doc_relation in batch:
            try:
                response = client.table('documents').update({
                    'doc_relation': doc_relation
                }).eq('pgpid', pgpid).execute()

                if response.data:
                    success_count += 1
                else:
                    # No row matched this pgpid. Normal: the CSV carries one row per
                    # fragment, so a multi-fragment document appears several times.
                    not_found_count += 1

            except Exception as e:
                print(f"  ERROR updating pgpid {pgpid}: {e}", file=sys.stderr)
                failed_count += 1

    return success_count, not_found_count, failed_count


def verify_doc_relations(client: Client, relations: dict) -> list:
    """Read every classified document back and compare. Returns [(pgpid, wanted, got)].

    The update loop infers success from `response.data`; this asks the database what it
    actually holds now. A partial outage, a silently ignored update, or a write to the
    wrong project all surface here rather than in the next sidecar export -- which cannot
    see them, because it compares row COUNTS and doc_relation changes none.
    """
    mismatches = []
    ids = sorted(relations)
    for start in range(0, len(ids), READBACK_CHUNK):
        chunk = ids[start:start + READBACK_CHUNK]
        rows = client.table('documents').select('pgpid,doc_relation').in_(
            'pgpid', chunk
        ).execute().data or []
        got = {row['pgpid']: row.get('doc_relation') for row in rows}
        for pgpid in chunk:
            if got.get(pgpid) != relations[pgpid]:
                mismatches.append((pgpid, relations[pgpid], got.get(pgpid, '<no row>')))
    return mismatches


def main():
    parser = argparse.ArgumentParser(
        description='Update doc_relation column in documents table'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        default=True,
        help='Validate and report without updating (default)'
    )
    parser.add_argument(
        '--execute',
        action='store_true',
        help='Actually update the database'
    )
    parser.add_argument(
        '--no-provenance-check',
        action='store_true',
        help='Classify from a transcriptions_linked.csv that does not match its provenance'
    )
    args = parser.parse_args()

    # --execute overrides --dry-run
    dry_run = not args.execute

    print("=" * 60)
    print("Update doc_relation column in documents table")
    print("=" * 60)
    print()

    # Load CSV data
    print(f"Loading doc_relation data from {TRANSCRIPTIONS_CSV}...")
    if not TRANSCRIPTIONS_CSV.exists():
        print(f"ERROR: CSV file not found: {TRANSCRIPTIONS_CSV}")
        sys.exit(1)

    # Read once; verify these bytes; parse these bytes.
    linked_raw = TRANSCRIPTIONS_CSV.read_bytes()
    require_verified_inputs(PGP_DATA_DIR, args.no_provenance_check,
                            contents={'transcriptions_linked.csv': linked_raw})

    relations, skipped = load_doc_relations_from_bytes(linked_raw)
    print(f"  Loaded {len(relations)} pgpid -> doc_relation mappings")
    print()

    # A row this script cannot use is a format change, not noise. The old code skipped it
    # with a bare `continue`, and a renamed column classified nothing at exit 0.
    if any(skipped.values()):
        print("ERROR: %d row(s) in transcriptions_linked.csv could not be used:"
              % sum(skipped.values()), file=sys.stderr)
        for reason, count in sorted(skipped.items()):
            if count:
                print("  %s: %d" % (reason, count), file=sys.stderr)
        print("Every row scripts/pgp_transcriptions_export.py writes has an integer pgpid and "
              "a doc_relation; this file does not. Regenerate it.", file=sys.stderr)
        return 1

    if not relations:
        print("ERROR: no classifications loaded -- a run that classifies nothing is not a "
              "success. Regenerate transcriptions_linked.csv and check its columns.",
              file=sys.stderr)
        return 1

    # Report statistics
    counts = defaultdict(int)
    for doc_relation in relations.values():
        counts[doc_relation] += 1

    print("doc_relation distribution:")
    for relation, count in sorted(counts.items(), key=lambda x: -x[1]):
        pct = (count / len(relations)) * 100
        print(f"  {relation}: {count} ({pct:.1f}%)")
    print()

    # Summary
    editions = counts.get('Digital Edition', 0)
    translations = counts.get('Digital Translation', 0)
    other = len(relations) - editions - translations

    print("Summary:")
    print(f"  Digital Editions (transcriptions to show): {editions}")
    print(f"  Digital Translations (to filter out): {translations}")
    if other > 0:
        print(f"  Other types: {other}")
    print()

    if dry_run:
        print("DRY RUN mode - no changes made")
        print()
        print("To update the database, run:")
        print("  python scripts/update_doc_relation.py --execute")
        return 0

    # Execute updates
    print("EXECUTE mode - updating database...")
    print()

    client = get_supabase_client()

    success, not_found, failed = batch_update_doc_relations(client, relations)

    print()
    print("=" * 60)
    print("Update complete")
    print("=" * 60)
    print(f"  Successful updates: {success}")
    print(f"  Not found in database: {not_found}")
    print(f"  FAILED (exceptions): {failed}")

    if not_found > 0:
        # The old note here claimed multi-fragment documents explained this. That was
        # FALSE: load_doc_relations() collapses the CSV to one mapping per pgpid, so
        # duplicate fragment rows cannot produce an unmatched update -- and
        # import_pgp_full.py upserts every document from the same source file immediately
        # before this runs. Measured on the staged corpus: zero classification ids are
        # missing from the loaded documents. So a no-match means the classification was
        # simply not applied, and the next export would ship a stale or NULL doc_relation.
        print()
        print(f"ERROR: {not_found} pgpid(s) matched no row in documents.", file=sys.stderr)
        print("Every pgpid classified here should already exist -- import_pgp_full.py",
              file=sys.stderr)
        print("upserts them from the same file. An unmatched update means the",
              file=sys.stderr)
        print("classification was NOT applied; exporting now would ship a stale or NULL",
              file=sys.stderr)
        print("doc_relation. Re-run scripts/import_pgp_full.py --execute first.",
              file=sys.stderr)
        return 1

    if failed:
        print()
        print(f"ERROR: {failed} update(s) raised. documents.doc_relation is now PARTIALLY",
              file=sys.stderr)
        print("updated, which is the worst of the three states: the next sidecar export",
              file=sys.stderr)
        print("will pass its own row-count and schema checks and ship a mix of fresh and",
              file=sys.stderr)
        print("stale classifications. Re-run this script before exporting.", file=sys.stderr)
        return 1

    # Do not trust the update responses; ask the database what it holds now.
    print()
    print("Reading every classification back...")
    mismatches = verify_doc_relations(client, relations)
    if mismatches:
        print(f"ERROR: {len(mismatches)} document(s) do not hold the classification just "
              "written:", file=sys.stderr)
        for pgpid, wanted, got in mismatches[:20]:
            print(f"  pgpid {pgpid}: wanted {wanted!r}, database has {got!r}", file=sys.stderr)
        if len(mismatches) > 20:
            print(f"  ... and {len(mismatches) - 20} more", file=sys.stderr)
        print("documents.doc_relation is NOT in the state this run reported. Do not export.",
              file=sys.stderr)
        return 1
    print(f"  {len(relations):,} classifications verified by read-back")

    return 0


if __name__ == '__main__':
    sys.exit(main())
