# -*- coding: utf-8 -*-
"""
Text Cleaner - Applies cleaning rules to normalize text before searching.

This module reads the cleaning rules generated by interactive_config.py
and applies them to clean text from various corpora.
"""

import os
import re
import json
from typing import Dict, Any, Tuple, Optional

from .config import CLEANING_RULES_FILE


class TextCleaner:
    """Cleans text according to configured rules."""

    def __init__(self, rules_path: str = None):
        self.rules_path = rules_path or CLEANING_RULES_FILE
        self.rules = {}
        self.metadata_extracted = {}
        self._load_rules()
        self._compile_patterns()

    def _load_rules(self):
        """Load cleaning rules from file."""
        if os.path.exists(self.rules_path):
            with open(self.rules_path, 'r', encoding='utf-8') as f:
                self.rules = json.load(f)
        else:
            print(f"Warning: No rules file found at {self.rules_path}")
            print("Using default cleaning rules.")
            self.rules = self._default_rules()

    def _default_rules(self) -> Dict[str, Any]:
        """Return sensible default rules."""
        return {
            'version': '1.0',
            'corpora': {
                'ja': {
                    'patterns': {
                        'curly_braces': {'action': 'remove_markers_keep_content'},
                        'square_brackets': {'action': 'remove_entirely'},
                        'parentheses': {'action': 'remove_markers_keep_content'},
                        'angle_brackets': {'action': 'remove_entirely'},
                        'nikud': {'action': 'remove_entirely'},
                        'taamim': {'action': 'remove_entirely'},
                    }
                },
                'maagarim': {
                    'patterns': {
                        'double_hash': {'action': 'extract_as_metadata'},
                        'double_greater': {'action': 'remove_markers_keep_content'},
                        'curly_braces': {'action': 'remove_markers_keep_content'},
                        'square_brackets': {'action': 'prefer_content'},
                        'parentheses': {'action': 'prefer_outside'},
                        'angle_brackets': {'action': 'remove_entirely'},
                        'dollar_markers': {'action': 'remove_entirely'},
                        'plus_angle': {'action': 'remove_entirely'},
                        'question_marks': {'action': 'remove_markers_keep_content'},
                        'nikud': {'action': 'remove_entirely'},
                        'taamim': {'action': 'remove_entirely'},
                        'maqaf': {'action': 'replace_with_space'},
                    }
                }
            }
        }

    def _compile_patterns(self):
        """Pre-compile regex patterns for efficiency."""
        self.compiled_patterns = {
            'curly_braces': (re.compile(r'\{([^}]*)\}'), r'\1'),
            'square_brackets': (re.compile(r'\[([^\]]*)\]'), r'\1'),
            'parentheses': (re.compile(r'\(([^)]*)\)'), r'\1'),
            'angle_brackets': (re.compile(r'<([^>]*)>'), r'\1'),
            'double_angle': (re.compile(r'<<([^>]*)>>'), r'\1'),
            'plus_angle': (re.compile(r'\+<[^>]*>'), ''),
            'tilde_braces': (re.compile(r'~\{[^}]*\}'), ''),
            'plus_braces': (re.compile(r'\+\{([^}]*)\}'), r'\1'),
            'double_hash': (re.compile(r'##([^#]*)##'), r'\1'),
            'double_greater': (re.compile(r'>>\s*'), ''),
            'dollar_markers': (re.compile(r'\$[^$]*\$'), ''),
            'pipe_markers': (re.compile(r'\|'), ' '),
            'question_marks': (re.compile(r'\?([^\s?]*)\?'), r'\1'),
            'superscript_nums': (re.compile(r'<\d+>'), ''),
            'nikud': (re.compile(r'[\u05B0-\u05BD\u05BF-\u05C7]'), ''),
            'taamim': (re.compile(r'[\u0591-\u05AF]'), ''),
            'maqaf': (re.compile(r'\u05BE'), ' '),
            'geresh': (re.compile(r'[\u05F3\u05F4]'), "'"),
        }

        # Pattern for extracting header metadata from Maagarim
        self.header_pattern = re.compile(r'##([^|]*)\|[^#]*##')

    def clean_text(self, text: str, corpus_id: str) -> Tuple[str, Dict[str, Any]]:
        """
        Clean text according to rules for the specified corpus.

        Args:
            text: The raw text to clean
            corpus_id: 'ja' or 'maagarim'

        Returns:
            Tuple of (cleaned_text, extracted_metadata)
        """
        metadata = {}
        corpus_rules = self.rules.get('corpora', {}).get(corpus_id, {}).get('patterns', {})

        # If no specific rules, use defaults
        if not corpus_rules:
            corpus_rules = self._default_rules()['corpora'].get(corpus_id, {}).get('patterns', {})

        # Extract metadata first (before other cleaning)
        if corpus_id == 'maagarim':
            headers = self.header_pattern.findall(text)
            if headers:
                metadata['headers'] = headers

        # Apply rules in order
        for pattern_name, rule in corpus_rules.items():
            action = rule.get('action', 'keep')

            if action == 'keep':
                continue

            if pattern_name not in self.compiled_patterns:
                continue

            pattern, default_replacement = self.compiled_patterns[pattern_name]

            if action == 'remove_entirely':
                text = pattern.sub('', text)

            elif action == 'remove_markers_keep_content':
                text = pattern.sub(default_replacement, text)

            elif action == 'replace_with_space':
                text = pattern.sub(' ', text)

            elif action == 'extract_as_metadata':
                matches = pattern.findall(text)
                if matches:
                    metadata[pattern_name] = matches
                text = pattern.sub('', text)

            elif action == 'prefer_content':
                # For patterns like (original)[correction] - keep correction
                text = pattern.sub(default_replacement, text)

            elif action == 'prefer_outside':
                # Remove bracketed content entirely
                text = pattern.sub('', text)

            elif action == 'custom':
                custom_pattern = rule.get('pattern', '')
                custom_replacement = rule.get('replacement', '')
                if custom_pattern:
                    text = re.sub(custom_pattern, custom_replacement, text)

        # Final cleanup
        text = self._final_cleanup(text)

        return text, metadata

    def _final_cleanup(self, text: str) -> str:
        """Final text cleanup steps."""
        # Normalize whitespace
        text = re.sub(r'\s+', ' ', text)

        # Remove leading/trailing whitespace
        text = text.strip()

        # Remove empty lines
        text = re.sub(r'\n\s*\n', '\n', text)

        return text

    def clean_ja_text(self, text: str) -> Tuple[str, Dict[str, Any]]:
        """Convenience method for cleaning Judeo-Arabic text."""
        return self.clean_text(text, 'ja')

    def clean_maagarim_text(self, text: str) -> Tuple[str, Dict[str, Any]]:
        """Convenience method for cleaning Maagarim text."""
        return self.clean_text(text, 'maagarim')


# Singleton instance
_cleaner = None


def get_cleaner() -> TextCleaner:
    """Get the singleton TextCleaner instance."""
    global _cleaner
    if _cleaner is None:
        _cleaner = TextCleaner()
    return _cleaner


def clean_text(text: str, corpus_id: str) -> Tuple[str, Dict[str, Any]]:
    """
    Clean text using the global cleaner instance.

    Args:
        text: The raw text to clean
        corpus_id: 'ja' or 'maagarim'

    Returns:
        Tuple of (cleaned_text, extracted_metadata)
    """
    return get_cleaner().clean_text(text, corpus_id)


# Quick test
if __name__ == '__main__':
    # Test Maagarim cleaning
    test_maagarim = """
##אנכי אזנתי לך קנוית קדם | המסירה: Oxford, Bodleian Library##
>> אנכי איזנתי לך קנוית קדם בה להתאימיך.
>> אמונה אומן בכתר כבודה להתמימיך.
>> $פז'$. מיכה אץ לבטל ''אנכי'' כקרא שם צלמו בשמי.
>> +<לכן70> צרעת נעמן הדביקתהו.
>> (זמר)[גחזי] רץ אחרי נעמן לרעתהו.
    """

    cleaner = TextCleaner()
    cleaned, metadata = cleaner.clean_maagarim_text(test_maagarim)

    print("Original:")
    print(test_maagarim)
    print("\nCleaned:")
    print(cleaned)
    print("\nMetadata:")
    print(metadata)
