from nicegui import app
from fastapi import Response
from web.state import state
import requests
from genizah_core import Config
import io
import openpyxl
from docx import Document
from urllib.parse import urlparse

# Import corrections API components
from backend.models.database import init_db
from backend.api.routes import auth, users, corrections, comments, documents

# Allowed domains for image proxy (prevents SSRF attacks)
ALLOWED_IMAGE_DOMAINS = [
    'rosetta.nli.org.il',
    'iiif.nli.org.il',
    'www.nli.org.il',
    'nli.org.il',
]

def init_api_routes():
    """Register API routes."""

    # Initialize corrections database
    try:
        init_db()
        print("Corrections database initialized")
    except Exception as e:
        print(f"Warning: Could not initialize corrections database: {e}")

    # Include corrections API routers
    app.include_router(auth.router, prefix="/api/v1", tags=["auth"])
    app.include_router(users.router, prefix="/api/v1", tags=["users"])
    app.include_router(corrections.router, prefix="/api/v1", tags=["corrections"])
    app.include_router(comments.router, prefix="/api/v1", tags=["comments"])
    app.include_router(documents.router, prefix="/api/v1", tags=["documents"])

    @app.get('/api/proxy_image')
    def proxy_image(url: str):
        """
        Proxy image requests to NLI to bypass Referer checks.
        Spoofs the Referer header to look like it's coming from nli.org.il.
        """
        if not url:
            return Response(status_code=400)

        # Validate URL format and domain to prevent SSRF attacks
        try:
            parsed = urlparse(url)
            if parsed.scheme not in ('http', 'https'):
                return Response(content="Invalid URL scheme", status_code=400)
            if not parsed.netloc:
                return Response(content="Invalid URL", status_code=400)
            if parsed.netloc not in ALLOWED_IMAGE_DOMAINS:
                return Response(content="Domain not allowed", status_code=403)
        except Exception:
            return Response(content="Invalid URL format", status_code=400)

        headers = dict(Config.HTTP_HEADERS)
        headers["Referer"] = "https://www.nli.org.il/"

        try:
            # Fetch the image with timeout
            resp = requests.get(url, headers=headers, timeout=10)
            if resp.status_code == 200:
                return Response(
                    content=resp.content,
                    media_type=resp.headers.get('Content-Type', 'image/jpeg')
                )
            else:
                return Response(status_code=resp.status_code)
        except requests.Timeout:
            print(f"Proxy timeout for URL: {url}")
            return Response(content="Request timeout", status_code=504)
        except Exception as e:
            print(f"Proxy error: {e}")
            return Response(status_code=500)

    @app.get('/api/export/excel')
    def export_excel():
        if not state.last_results:
            return Response("No results to export", status_code=400)

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Genizah Results"

        headers = ["Shelfmark", "Title", "System ID", "Score", "Snippet", "Full Text"]
        ws.append(headers)

        for res in state.last_results:
            display = res.get('display', {})
            row = [
                display.get('shelfmark', ''),
                display.get('title', ''),
                display.get('id', ''),
                str(res.get('sort_score', '')),
                res.get('snippet', '').replace('*', ''),
                res.get('full_text', '')[:32000] # Excel cell limit safety
            ]
            # Sanitize for illegal chars
            clean_row = []
            for cell in row:
                if isinstance(cell, str):
                    # Remove illegal chars (XML 1.0 invalid chars)
                    cell = "".join(ch for ch in cell if (0x20 <= ord(ch) <= 0xD7FF) or (0xE000 <= ord(ch) <= 0xFFFD) or ch in "\n\r\t")
                clean_row.append(cell)
            ws.append(clean_row)

        # Add credits at the bottom
        ws.append([])
        ws.append([])
        ws.append(['Credits'])
        ws.append(['Generated by Genizah Search Pro (Web Version)'])
        ws.append(['Data Source: MiDRASH Automatic Transcriptions (Stoekl Ben Ezra et al., 2025)'])
        ws.append(['Dataset: https://doi.org/10.5281/zenodo.17734473'])
        ws.append(['Citation: Stoekl Ben Ezra, D., Bambaci, L., Kiessling, B., Lapin, H., Ezer, N., Lolli, E., Rustow, M., Dershowitz, N., Kurar Barakat, B., Gogawale, S., Shmidman, A., Lavee, M., Siew, T., Raziel Kretzmer, V., Vasyutinsky Shapira, D., Olszowy-Schlanger, J., & Gila, Y. (2025). MiDRASH Automatic Transcriptions. Zenodo. https://doi.org/10.5281/zenodo.17734473'])

        stream = io.BytesIO()
        wb.save(stream)
        stream.seek(0)

        return Response(
            content=stream.read(),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": "attachment; filename=genizah_results.xlsx"}
        )

    @app.get('/api/export/word')
    def export_word():
        if not state.last_results:
            return Response("No results to export", status_code=400)

        doc = Document()
        doc.add_heading('Genizah Search Results', 0)

        for i, res in enumerate(state.last_results):
            display = res.get('display', {})
            shelf = display.get('shelfmark', 'Unknown')
            title = display.get('title', '')

            p = doc.add_paragraph()
            p.add_run(f"{i+1}. {shelf}").bold = True
            if title:
                p.add_run(f" - {title}")

            if res.get('snippet'):
                doc.add_paragraph(res['snippet'].replace('*', ''))

            doc.add_paragraph(f"System ID: {display.get('id', '')}")
            doc.add_paragraph("_" * 40)

        # Add credits
        doc.add_page_break()
        doc.add_heading('Credits', 1)
        doc.add_paragraph('Generated by Genizah Search Pro (Web Version)')
        doc.add_paragraph('Data Source: MiDRASH Automatic Transcriptions (Stoekl Ben Ezra et al., 2025)')
        doc.add_paragraph('Dataset available at: https://doi.org/10.5281/zenodo.17734473')
        doc.add_paragraph()
        citation = doc.add_paragraph('Full Citation: ')
        citation.add_run('Stoekl Ben Ezra, D., Bambaci, L., Kiessling, B., Lapin, H., Ezer, N., Lolli, E., Rustow, M., Dershowitz, N., Kurar Barakat, B., Gogawale, S., Shmidman, A., Lavee, M., Siew, T., Raziel Kretzmer, V., Vasyutinsky Shapira, D., Olszowy-Schlanger, J., & Gila, Y. (2025). MiDRASH Automatic Transcriptions. Zenodo. https://doi.org/10.5281/zenodo.17734473').italic = True

        stream = io.BytesIO()
        doc.save(stream)
        stream.seek(0)

        return Response(
            content=stream.read(),
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": "attachment; filename=genizah_results.docx"}
        )

    @app.get('/api/export/parallels/excel')
    def export_parallels_excel():
        """Export parallels results to Excel."""
        from nicegui import app as nicegui_app

        parallels_results = nicegui_app.storage.user.get('parallels_results', [])
        if not parallels_results:
            return Response("No parallels results to export", status_code=400)

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Parallels Results"

        headers = ["#", "Shelfmark", "Title", "Score", "Source Context", "Manuscript Match"]
        ws.append(headers)

        for idx, item in enumerate(parallels_results, 1):
            score = item.get('score', 0)
            raw_header = item.get('raw_header', '')

            # Extract metadata
            sys_id = None
            shelfmark = 'Unknown'
            title = ''

            if raw_header and state.meta_mgr:
                try:
                    import re
                    sys_match = re.search(r'(99\d{8,})', raw_header)
                    if sys_match:
                        sys_id = sys_match.group(1)
                        shelf_temp, title_temp = state.meta_mgr.get_meta_for_id(sys_id)
                        shelfmark = shelf_temp or shelfmark
                        title = title_temp or ''
                except Exception:
                    pass

            source_ctx = item.get('source_ctx', '').replace('*', '')
            ms_text = item.get('text', '').replace('*', '')

            row = [idx, shelfmark, title, score, source_ctx, ms_text]

            # Sanitize for illegal chars
            clean_row = []
            for cell in row:
                if isinstance(cell, str):
                    cell = "".join(ch for ch in cell if (0x20 <= ord(ch) <= 0xD7FF) or (0xE000 <= ord(ch) <= 0xFFFD) or ch in "\n\r\t")
                clean_row.append(cell)
            ws.append(clean_row)

        # Add credits at the bottom
        ws.append([])
        ws.append([])
        ws.append(['Credits'])
        ws.append(['Generated by Genizah Search Pro (Web Version)'])
        ws.append(['Data Source: MiDRASH Automatic Transcriptions (Stoekl Ben Ezra et al., 2025)'])
        ws.append(['Dataset: https://doi.org/10.5281/zenodo.17734473'])
        ws.append(['Citation: Stoekl Ben Ezra, D., Bambaci, L., Kiessling, B., Lapin, H., Ezer, N., Lolli, E., Rustow, M., Dershowitz, N., Kurar Barakat, B., Gogawale, S., Shmidman, A., Lavee, M., Siew, T., Raziel Kretzmer, V., Vasyutinsky Shapira, D., Olszowy-Schlanger, J., & Gila, Y. (2025). MiDRASH Automatic Transcriptions. Zenodo. https://doi.org/10.5281/zenodo.17734473'])

        stream = io.BytesIO()
        wb.save(stream)
        stream.seek(0)

        return Response(
            content=stream.read(),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": "attachment; filename=parallels_results.xlsx"}
        )

    @app.get('/api/export/parallels/word')
    def export_parallels_word():
        """Export parallels results to Word."""
        from nicegui import app as nicegui_app

        parallels_results = nicegui_app.storage.user.get('parallels_results', [])
        if not parallels_results:
            return Response("No parallels results to export", status_code=400)

        doc = Document()
        doc.add_heading('Genizah Parallels Search Results', 0)

        for idx, item in enumerate(parallels_results, 1):
            score = item.get('score', 0)
            raw_header = item.get('raw_header', '')

            # Extract metadata
            shelfmark = 'Unknown'
            title = ''

            if raw_header and state.meta_mgr:
                try:
                    import re
                    sys_match = re.search(r'(99\d{8,})', raw_header)
                    if sys_match:
                        sys_id = sys_match.group(1)
                        shelf_temp, title_temp = state.meta_mgr.get_meta_for_id(sys_id)
                        shelfmark = shelf_temp or shelfmark
                        title = title_temp or ''
                except Exception:
                    pass

            p = doc.add_paragraph()
            p.add_run(f"{idx}. {shelfmark}").bold = True
            p.add_run(f" - Score: {score}")
            if title:
                doc.add_paragraph(title)

            doc.add_paragraph("Source Context:").bold = True
            doc.add_paragraph(item.get('source_ctx', '').replace('*', ''))

            doc.add_paragraph("Manuscript Match:").bold = True
            doc.add_paragraph(item.get('text', '').replace('*', ''))

            doc.add_paragraph("_" * 60)

        # Add credits
        doc.add_page_break()
        doc.add_heading('Credits', 1)
        doc.add_paragraph('Generated by Genizah Search Pro (Web Version)')
        doc.add_paragraph('Data Source: MiDRASH Automatic Transcriptions (Stoekl Ben Ezra et al., 2025)')
        doc.add_paragraph('Dataset available at: https://doi.org/10.5281/zenodo.17734473')
        doc.add_paragraph()
        citation = doc.add_paragraph('Full Citation: ')
        citation.add_run('Stoekl Ben Ezra, D., Bambaci, L., Kiessling, B., Lapin, H., Ezer, N., Lolli, E., Rustow, M., Dershowitz, N., Kurar Barakat, B., Gogawale, S., Shmidman, A., Lavee, M., Siew, T., Raziel Kretzmer, V., Vasyutinsky Shapira, D., Olszowy-Schlanger, J., & Gila, Y. (2025). MiDRASH Automatic Transcriptions. Zenodo. https://doi.org/10.5281/zenodo.17734473').italic = True

        stream = io.BytesIO()
        doc.save(stream)
        stream.seek(0)

        return Response(
            content=stream.read(),
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": "attachment; filename=parallels_results.docx"}
        )

    @app.get('/api/export/browse/word')
    def export_browse_word():
        """Export current browse page to Word."""
        from nicegui import app as nicegui_app

        browse_data = nicegui_app.storage.user.get('browse_export_data')
        if not browse_data:
            return Response("No browse data to export", status_code=400)

        doc = Document()
        doc.add_heading('Genizah Manuscript', 0)

        # Manuscript info
        if browse_data.get('shelfmark'):
            doc.add_heading(browse_data['shelfmark'], 1)
        if browse_data.get('title'):
            doc.add_paragraph(browse_data['title'])

        if browse_data.get('sys_id'):
            doc.add_paragraph(f"System ID: {browse_data['sys_id']}")

        doc.add_paragraph("_" * 60)

        # Text content
        if browse_data.get('view_all') and browse_data.get('pages'):
            doc.add_heading('Full Manuscript', 2)
            for page_data in browse_data['pages']:
                doc.add_heading(f"Page {page_data.get('p_num', '?')}", 3)
                if page_data.get('text'):
                    doc.add_paragraph(page_data['text'])
        elif browse_data.get('text'):
            doc.add_heading(f"Page {browse_data.get('p_num', '?')}", 2)
            doc.add_paragraph(browse_data['text'])

        # Add credits
        doc.add_page_break()
        doc.add_heading('Credits', 1)
        doc.add_paragraph('Generated by Genizah Search Pro (Web Version)')
        doc.add_paragraph('Data Source: MiDRASH Automatic Transcriptions (Stoekl Ben Ezra et al., 2025)')
        doc.add_paragraph('Dataset available at: https://doi.org/10.5281/zenodo.17734473')
        doc.add_paragraph()
        citation = doc.add_paragraph('Full Citation: ')
        citation.add_run('Stoekl Ben Ezra, D., Bambaci, L., Kiessling, B., Lapin, H., Ezer, N., Lolli, E., Rustow, M., Dershowitz, N., Kurar Barakat, B., Gogawale, S., Shmidman, A., Lavee, M., Siew, T., Raziel Kretzmer, V., Vasyutinsky Shapira, D., Olszowy-Schlanger, J., & Gila, Y. (2025). MiDRASH Automatic Transcriptions. Zenodo. https://doi.org/10.5281/zenodo.17734473').italic = True

        stream = io.BytesIO()
        doc.save(stream)
        stream.seek(0)

        return Response(
            content=stream.read(),
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": "attachment; filename=manuscript.docx"}
        )

    @app.get('/api/export/list/{list_id}/excel')
    def export_list_excel(list_id: str):
        """Export a specific list to Excel."""
        if not state.lists_mgr:
            return Response("Lists manager not available", status_code=400)

        list_data = state.lists_mgr.data.get('lists', {}).get(list_id)
        if not list_data:
            return Response("List not found", status_code=404)

        items = list_data.get('items', [])
        if not items:
            return Response("List is empty", status_code=400)

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = list_data.get('name', 'List')[:31]  # Excel sheet name limit

        headers = ["#", "Shelfmark", "Title", "System ID", "FL ID", "Notes", "Added"]
        ws.append(headers)

        for idx, item in enumerate(items, 1):
            sys_id = item.get('sys_id', '')
            shelfmark = 'Unknown'
            title = ''

            if sys_id and state.meta_mgr:
                try:
                    shelf_temp, title_temp = state.meta_mgr.get_meta_for_id(sys_id)
                    shelfmark = shelf_temp or shelfmark
                    title = title_temp or ''
                except Exception:
                    pass

            row = [
                idx,
                shelfmark,
                title,
                sys_id,
                item.get('fl_id', ''),
                item.get('note', ''),
                item.get('added', '')
            ]

            # Sanitize for illegal chars
            clean_row = []
            for cell in row:
                if isinstance(cell, str):
                    cell = "".join(ch for ch in cell if (0x20 <= ord(ch) <= 0xD7FF) or (0xE000 <= ord(ch) <= 0xFFFD) or ch in "\n\r\t")
                clean_row.append(cell)
            ws.append(clean_row)

        # Add credits at the bottom
        ws.append([])
        ws.append([])
        ws.append(['Credits'])
        ws.append(['Generated by Genizah Search Pro (Web Version)'])
        ws.append(['Data Source: MiDRASH Automatic Transcriptions (Stoekl Ben Ezra et al., 2025)'])
        ws.append(['Dataset: https://doi.org/10.5281/zenodo.17734473'])
        ws.append(['Citation: Stoekl Ben Ezra, D., Bambaci, L., Kiessling, B., Lapin, H., Ezer, N., Lolli, E., Rustow, M., Dershowitz, N., Kurar Barakat, B., Gogawale, S., Shmidman, A., Lavee, M., Siew, T., Raziel Kretzmer, V., Vasyutinsky Shapira, D., Olszowy-Schlanger, J., & Gila, Y. (2025). MiDRASH Automatic Transcriptions. Zenodo. https://doi.org/10.5281/zenodo.17734473'])

        stream = io.BytesIO()
        wb.save(stream)
        stream.seek(0)

        filename = f"{list_data.get('name', 'list').replace(' ', '_')}.xlsx"
        return Response(
            content=stream.read(),
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
