# -*- coding: utf-8 -*-
"""
Unified Export Service for GenizahSearch.

This module centralizes all export functionality to ensure:
1. Consistent RTL formatting for Hebrew text
2. Uniform credits and citation
3. Proper text sanitization
4. Reusable utilities across all export types (Excel, Word)

Author: GenizahSearch Team
"""

import io
import re
from typing import List, Dict, Any, Optional
from dataclasses import dataclass

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill

from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt


# Constants
HEBREW_FONT_NAME = "David"
CREDITS_TEXT = [
    'Generated by Dicta Genizah Search (Web Version)',
    'Data Source: MiDRASH Automatic Transcriptions (Stoekl Ben Ezra et al., 2025)',
    'Dataset: https://doi.org/10.5281/zenodo.17734473',
    'Citation: Stoekl Ben Ezra, D., Bambaci, L., Kiessling, B., Lapin, H., Ezer, N., Lolli, E., Rustow, M., Dershowitz, N., Kurar Barakat, B., Gogawale, S., Shmidman, A., Lavee, M., Siew, T., Raziel Kretzmer, V., Vasyutinsky Shapira, D., Olszowy-Schlanger, J., & Gila, Y. (2025). MiDRASH Automatic Transcriptions. Zenodo. https://doi.org/10.5281/zenodo.17734473',
]


# ============================================================================
# Text Processing Utilities
# Import from shared module for consistency between Desktop and Web
# ============================================================================

from shared_export_utils import (
    sanitize_text_for_excel,
    clean_text_single_line,
    remove_highlight_markers,
    make_safe_filename,
    encode_filename_for_header,
    contains_any_term,
    extract_search_terms,
)


# ============================================================================
# Word Document RTL Utilities
# ============================================================================

def set_paragraph_rtl(paragraph):
    """Set RTL direction and right alignment for a paragraph containing Hebrew text."""
    paragraph.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT
    paragraph.paragraph_format.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT
    ppr = paragraph._p.get_or_add_pPr()
    bidi = ppr.find(qn("w:bidi"))
    if bidi is None:
        bidi = OxmlElement("w:bidi")
        ppr.append(bidi)
    bidi.set(qn("w:val"), "1")


def set_run_rtl_font(run, font_size: Optional[int] = None):
    """Set Hebrew-compatible font for a run and mark it as RTL."""
    run.font.name = HEBREW_FONT_NAME
    r = run._r
    rPr = r.get_or_add_rPr()

    # Set cs (complex script) font for Hebrew
    cs_font = rPr.find(qn("w:rFonts"))
    if cs_font is None:
        cs_font = OxmlElement("w:rFonts")
        rPr.insert(0, cs_font)
    cs_font.set(qn("w:cs"), HEBREW_FONT_NAME)
    cs_font.set(qn("w:ascii"), HEBREW_FONT_NAME)
    cs_font.set(qn("w:hAnsi"), HEBREW_FONT_NAME)

    # Mark as RTL text
    rtl = rPr.find(qn("w:rtl"))
    if rtl is None:
        rtl = OxmlElement("w:rtl")
        rPr.append(rtl)

    if font_size:
        run.font.size = Pt(font_size)


def add_hebrew_paragraph(doc: Document, text: str, bold: bool = False, font_size: Optional[int] = None) -> None:
    """Add a right-aligned Hebrew paragraph to a Word document."""
    p = doc.add_paragraph()
    run = p.add_run(text)
    if bold:
        run.bold = True
    set_run_rtl_font(run, font_size)
    set_paragraph_rtl(p)


def add_highlighted_hebrew_paragraph(doc: Document, text: str) -> None:
    """
    Add a Hebrew paragraph with highlighted terms (marked with *).
    Text between * markers will be bold with yellow highlight.
    """
    p = doc.add_paragraph()
    parts = text.split('*')
    is_highlighted = False

    for i, part in enumerate(parts):
        if not part:
            is_highlighted = not is_highlighted
            continue
        run = p.add_run(part)
        set_run_rtl_font(run)
        if is_highlighted:
            run.bold = True
            # Add yellow highlight
            rPr = run._r.get_or_add_rPr()
            highlight = OxmlElement('w:highlight')
            highlight.set(qn('w:val'), 'yellow')
            rPr.append(highlight)
        is_highlighted = not is_highlighted

    set_paragraph_rtl(p)


def add_word_credits(doc: Document) -> None:
    """Add standard credits section to a Word document."""
    doc.add_page_break()
    doc.add_heading('Credits', 1)
    doc.add_paragraph(CREDITS_TEXT[0])
    doc.add_paragraph(CREDITS_TEXT[1])
    doc.add_paragraph(f'Dataset available at: {CREDITS_TEXT[2].replace("Dataset: ", "")}')
    doc.add_paragraph()
    citation_p = doc.add_paragraph('Full Citation: ')
    citation_run = citation_p.add_run(CREDITS_TEXT[3].replace('Citation: ', ''))
    citation_run.italic = True


# ============================================================================
# Excel Utilities
# ============================================================================

@dataclass
class ExcelColumnConfig:
    """Configuration for an Excel column."""
    header: str
    width: int
    alignment: str  # 'rtl', 'ltr', 'center'
    highlight_on_match: bool = False


def create_excel_workbook(
    sheet_name: str = "Results",
    rtl_sheet: bool = True
) -> tuple:
    """
    Create a new Excel workbook with basic configuration.
    Returns (workbook, worksheet).
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_name[:31]  # Excel sheet name limit
    if rtl_sheet:
        ws.sheet_view.rightToLeft = True
    return wb, ws


def style_excel_header(ws, headers: List[str]) -> None:
    """Apply standard header styling to the first row."""
    ws.append(headers)
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="4F81BD", end_color="4F81BD", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center")

    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment


def set_excel_column_widths(ws, widths: Dict[str, int]) -> None:
    """Set column widths. Keys are column letters (A, B, C, ...)."""
    for col_letter, width in widths.items():
        ws.column_dimensions[col_letter].width = width


def get_cell_alignment(align_type: str) -> Alignment:
    """Get an Alignment object based on alignment type."""
    if align_type == 'rtl':
        return Alignment(horizontal="right", vertical="top", wrap_text=False, readingOrder=2)
    elif align_type == 'center':
        return Alignment(horizontal="center", vertical="top")
    else:  # 'ltr'
        return Alignment(horizontal="left", vertical="top")


def add_excel_credits(ws) -> None:
    """Add standard credits section at the bottom of the worksheet."""
    ws.append([])
    ws.append([])
    credits_start_row = ws.max_row + 1
    ws.append(['Credits'])
    for credit_line in CREDITS_TEXT:
        ws.append([credit_line])

    # Style credits
    credits_font = Font(italic=True, color="555555")
    for row_idx in range(credits_start_row, ws.max_row + 1):
        cell = ws.cell(row=row_idx, column=1)
        cell.font = credits_font


def save_workbook_to_bytes(wb) -> bytes:
    """Save workbook to a bytes buffer and return the content."""
    stream = io.BytesIO()
    wb.save(stream)
    stream.seek(0)
    return stream.read()


def save_document_to_bytes(doc: Document) -> bytes:
    """Save Word document to a bytes buffer and return the content."""
    stream = io.BytesIO()
    doc.save(stream)
    stream.seek(0)
    return stream.read()


# ============================================================================
# High-Level Export Functions
# ============================================================================

class ExportService:
    """
    Unified service for exporting search results, lists, and other data.
    Ensures consistent formatting and error handling across all exports.
    """

    def __init__(self, meta_mgr=None):
        """
        Initialize the export service.

        Args:
            meta_mgr: MetadataManager instance for resolving shelfmarks/titles.
        """
        self.meta_mgr = meta_mgr

    def get_metadata(self, sys_id: str) -> tuple:
        """Get shelfmark and title for a system ID."""
        if not sys_id or not self.meta_mgr:
            return ('Unknown', '')
        try:
            shelfmark, title = self.meta_mgr.get_meta_for_id(sys_id)
            return (shelfmark or 'Unknown', title or '')
        except Exception:
            return ('Unknown', '')

    def get_library_code(self, sys_id: str) -> str:
        """Get library code for a system ID."""
        if not sys_id or not self.meta_mgr:
            return ''
        try:
            return self.meta_mgr.get_library_for_id(sys_id) or ''
        except Exception:
            return ''

    def get_library_display(self, library_code: str, short: bool = True) -> str:
        """Get library display name from code."""
        if not library_code:
            return ''
        try:
            from genizah_core import get_library_display as core_get_library_display
            from web.translations import get_language
            return core_get_library_display(library_code, short=short, lang=get_language())
        except Exception:
            return library_code  # Fallback to code itself

    def export_search_results_excel(
        self,
        results: List[Dict[str, Any]],
        search_query: str = ""
    ) -> tuple:
        """
        Export search results to Excel format.

        Returns:
            (bytes, filename) tuple
        """
        if not results:
            raise ValueError("No results to export")

        search_terms = extract_search_terms(search_query)
        wb, ws = create_excel_workbook("Genizah Results")

        headers = ["Shelfmark", "Library", "Title", "System ID", "Score", "Snippet", "Full Text"]
        style_excel_header(ws, headers)

        set_excel_column_widths(ws, {
            'A': 25, 'B': 15, 'C': 35, 'D': 18, 'E': 10, 'F': 50, 'G': 80,
        })

        highlight_fill = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")
        rtl_align = get_cell_alignment('rtl')
        ltr_align = get_cell_alignment('ltr')
        center_align = get_cell_alignment('center')

        for res in results:
            display = res.get('display', {})
            snippet = clean_text_single_line(remove_highlight_markers(res.get('snippet', '')))
            full_text = clean_text_single_line(res.get('full_text', ''))[:32000]

            # Get full library name
            library_code = display.get('library_code', '')
            library_name = self.get_library_display(library_code, short=False) if library_code else ''

            row = [
                sanitize_text_for_excel(display.get('shelfmark', '')),
                sanitize_text_for_excel(library_name),
                sanitize_text_for_excel(display.get('title', '')),
                sanitize_text_for_excel(display.get('id', '')),
                str(res.get('sort_score', '')),
                sanitize_text_for_excel(snippet),
                sanitize_text_for_excel(full_text),
            ]
            ws.append(row)

            current_row = ws.max_row
            ws.cell(row=current_row, column=1).alignment = rtl_align
            ws.cell(row=current_row, column=2).alignment = ltr_align  # Library code is LTR
            ws.cell(row=current_row, column=3).alignment = rtl_align
            ws.cell(row=current_row, column=4).alignment = ltr_align
            ws.cell(row=current_row, column=5).alignment = center_align

            snippet_cell = ws.cell(row=current_row, column=6)
            snippet_cell.alignment = rtl_align
            if contains_any_term(snippet, search_terms):
                snippet_cell.fill = highlight_fill

            fulltext_cell = ws.cell(row=current_row, column=7)
            fulltext_cell.alignment = rtl_align
            if contains_any_term(full_text, search_terms):
                fulltext_cell.fill = highlight_fill

        add_excel_credits(ws)

        filename = make_safe_filename(search_query) + ".xlsx"
        return save_workbook_to_bytes(wb), filename

    def export_search_results_word(
        self,
        results: List[Dict[str, Any]],
        search_query: str = ""
    ) -> tuple:
        """
        Export search results to Word format.

        Returns:
            (bytes, filename) tuple
        """
        if not results:
            raise ValueError("No results to export")

        doc = Document()
        title_text = f'Genizah Search Results: "{search_query}"' if search_query else 'Genizah Search Results'
        doc.add_heading(title_text, 0)

        for i, res in enumerate(results):
            display = res.get('display', {})
            shelf = display.get('shelfmark', 'Unknown')
            title = display.get('title', '')
            library_code = display.get('library_code', '')

            # Get library name
            library_name = ''
            if library_code:
                library_name = self.get_library_display(library_code, short=False)

            # Build display header with library
            display_header = f"{library_name}, {shelf}" if library_name else shelf

            # Header with library and shelfmark
            p = doc.add_paragraph()
            run = p.add_run(f"{i+1}. {display_header}")
            run.bold = True
            set_run_rtl_font(run)
            if title:
                title_run = p.add_run(f" - {title}")
                set_run_rtl_font(title_run)
            set_paragraph_rtl(p)

            # Snippet with highlighting
            if res.get('snippet'):
                add_highlighted_hebrew_paragraph(doc, res['snippet'])

            # System ID
            doc.add_paragraph(f"System ID: {display.get('id', '')}")
            doc.add_paragraph("_" * 40)

        add_word_credits(doc)

        # Filename with "search" suffix
        filename = make_safe_filename(search_query, default="genizah") + "_search.docx"
        return save_document_to_bytes(doc), filename

    def export_list_excel(
        self,
        list_id: str,
        list_name: str,
        items: List[Dict[str, Any]]
    ) -> tuple:
        """
        Export a personal list to Excel format.

        Returns:
            (bytes, filename) tuple
        """
        if not items:
            raise ValueError("List is empty")

        wb, ws = create_excel_workbook(list_name)

        headers = ["#", "Shelfmark", "Library", "Title", "System ID", "FL ID", "Notes", "Added"]
        style_excel_header(ws, headers)

        set_excel_column_widths(ws, {
            'A': 6, 'B': 25, 'C': 15, 'D': 35, 'E': 18, 'F': 12, 'G': 40, 'H': 18,
        })

        rtl_align = get_cell_alignment('rtl')
        ltr_align = get_cell_alignment('ltr')
        center_align = get_cell_alignment('center')

        for idx, item in enumerate(items, 1):
            sys_id = item.get('sys_id', '')
            shelfmark, title = self.get_metadata(sys_id)
            library_code = self.get_library_code(sys_id)
            # Get full library name
            library_name = self.get_library_display(library_code, short=False) if library_code else ''
            notes = clean_text_single_line(item.get('note', ''))

            row = [
                idx,
                sanitize_text_for_excel(shelfmark),
                sanitize_text_for_excel(library_name),
                sanitize_text_for_excel(title),
                sanitize_text_for_excel(sys_id),
                sanitize_text_for_excel(item.get('fl_id', '')),
                sanitize_text_for_excel(notes),
                sanitize_text_for_excel(item.get('added', '')),
            ]
            ws.append(row)

            current_row = ws.max_row
            ws.cell(row=current_row, column=1).alignment = center_align
            ws.cell(row=current_row, column=2).alignment = rtl_align
            ws.cell(row=current_row, column=3).alignment = ltr_align  # Library code is LTR
            ws.cell(row=current_row, column=4).alignment = rtl_align
            ws.cell(row=current_row, column=5).alignment = ltr_align
            ws.cell(row=current_row, column=6).alignment = ltr_align
            ws.cell(row=current_row, column=7).alignment = rtl_align
            ws.cell(row=current_row, column=8).alignment = ltr_align

        add_excel_credits(ws)

        safe_name = list_name.replace(' ', '_')
        filename = f"{safe_name}.xlsx"
        return save_workbook_to_bytes(wb), filename

    def export_parallels_excel(
        self,
        main_results: List[Dict[str, Any]],
        filtered_results: List[Dict[str, Any]] = None,
        source_text: str = ""
    ) -> tuple:
        """
        Export parallels results to Excel format.

        Returns:
            (bytes, filename) tuple
        """
        if not main_results and not filtered_results:
            raise ValueError("No parallels results to export")

        wb, ws = create_excel_workbook("Parallels Results")

        headers = ["#", "Shelfmark", "Library", "Title", "Score", "Source Context", "Manuscript Match", "Filtered"]
        style_excel_header(ws, headers)

        set_excel_column_widths(ws, {
            'A': 6, 'B': 25, 'C': 15, 'D': 35, 'E': 10, 'F': 50, 'G': 60, 'H': 10,
        })

        rtl_align = get_cell_alignment('rtl')
        ltr_align = get_cell_alignment('ltr')
        center_align = get_cell_alignment('center')

        def add_results(results: List[Dict], start_idx: int, is_filtered: bool) -> int:
            for idx, item in enumerate(results, start_idx):
                raw_header = item.get('raw_header', '')
                sys_id = None
                shelfmark, title = 'Unknown', ''
                library_name = ''

                if raw_header:
                    sys_match = re.search(r'(99\d{8,})', raw_header)
                    if sys_match:
                        sys_id = sys_match.group(1)
                        shelfmark, title = self.get_metadata(sys_id)
                        library_code = self.get_library_code(sys_id)
                        # Get full library name
                        library_name = self.get_library_display(library_code, short=False) if library_code else ''

                source_ctx = clean_text_single_line(remove_highlight_markers(item.get('source_ctx', '')))
                ms_text = clean_text_single_line(remove_highlight_markers(item.get('text', '')))

                row = [
                    idx,
                    sanitize_text_for_excel(shelfmark),
                    sanitize_text_for_excel(library_name),
                    sanitize_text_for_excel(title),
                    item.get('score', 0),
                    sanitize_text_for_excel(source_ctx),
                    sanitize_text_for_excel(ms_text),
                    'Yes' if is_filtered else '',
                ]
                ws.append(row)

                current_row = ws.max_row
                ws.cell(row=current_row, column=1).alignment = center_align  # #
                ws.cell(row=current_row, column=2).alignment = rtl_align     # Shelfmark
                ws.cell(row=current_row, column=3).alignment = ltr_align     # Library
                ws.cell(row=current_row, column=4).alignment = rtl_align     # Title
                ws.cell(row=current_row, column=5).alignment = center_align  # Score
                ws.cell(row=current_row, column=6).alignment = rtl_align     # Source Context
                ws.cell(row=current_row, column=7).alignment = rtl_align     # Manuscript Match
                ws.cell(row=current_row, column=8).alignment = center_align  # Filtered

            return start_idx + len(results)

        next_idx = add_results(main_results or [], 1, False)
        if filtered_results:
            add_results(filtered_results, next_idx, True)

        add_excel_credits(ws)

        # Filename: first words of source text + "_parallels"
        if source_text:
            filename_base = source_text[:30].strip()
            filename = make_safe_filename(filename_base, default="parallels") + "_parallels.xlsx"
        else:
            filename = "parallels_results.xlsx"

        return save_workbook_to_bytes(wb), filename

    def export_parallels_word(
        self,
        main_results: List[Dict[str, Any]],
        filtered_results: List[Dict[str, Any]] = None,
        source_text: str = ""
    ) -> tuple:
        """
        Export parallels results to Word format.

        Returns:
            (bytes, filename) tuple
        """
        if not main_results and not filtered_results:
            raise ValueError("No parallels results to export")

        doc = Document()

        # Build title with source text preview
        if source_text:
            # Take first ~50 chars of source text for title
            source_preview = source_text[:50].strip()
            if len(source_text) > 50:
                source_preview += "..."
            doc.add_heading(f'Parallels for: "{source_preview}"', 0)
        else:
            doc.add_heading('Genizah Parallels Search Results', 0)

        def add_results(results: List[Dict], start_idx: int, section_title: str = None) -> int:
            if section_title:
                doc.add_heading(section_title, 1)

            for idx, item in enumerate(results, start_idx):
                raw_header = item.get('raw_header', '')
                shelfmark, title = 'Unknown', ''
                sys_id = ''

                if raw_header:
                    sys_match = re.search(r'(99\d{8,})', raw_header)
                    if sys_match:
                        sys_id = sys_match.group(1)
                        shelfmark, title = self.get_metadata(sys_id)

                # Get library info
                library_name = ''
                if sys_id:
                    library_code = self.get_library_code(sys_id)
                    if library_code:
                        library_name = self.get_library_display(library_code, short=False)

                # Build display header with library
                display_header = f"{library_name}, {shelfmark}" if library_name else shelfmark

                # Header
                p = doc.add_paragraph()
                shelf_run = p.add_run(f"{idx}. {display_header}")
                shelf_run.bold = True
                set_run_rtl_font(shelf_run)
                p.add_run(f" - Score: {item.get('score', 0)}")
                set_paragraph_rtl(p)

                # Title
                if title:
                    add_hebrew_paragraph(doc, title)

                # Source Context
                label_p = doc.add_paragraph()
                label_p.add_run("Source Context:").bold = True
                add_hebrew_paragraph(doc, remove_highlight_markers(item.get('source_ctx', '')))

                # Manuscript Match
                label_p2 = doc.add_paragraph()
                label_p2.add_run("Manuscript Match:").bold = True
                add_hebrew_paragraph(doc, remove_highlight_markers(item.get('text', '')))

                doc.add_paragraph("_" * 60)

            return start_idx + len(results)

        next_idx = add_results(main_results or [], 1)
        if filtered_results:
            add_results(filtered_results, next_idx, "Filtered Results (found in source texts)")

        add_word_credits(doc)

        # Filename: first words of source text + "_parallels"
        if source_text:
            # Take first ~30 chars for filename
            filename_base = source_text[:30].strip()
            filename = make_safe_filename(filename_base, default="parallels") + "_parallels.docx"
        else:
            filename = "parallels_results.docx"

        return save_document_to_bytes(doc), filename

    def export_browse_word(
        self,
        browse_data: Dict[str, Any]
    ) -> tuple:
        """
        Export browse page data to Word format.

        Returns:
            (bytes, filename) tuple
        """
        if not browse_data:
            raise ValueError("No browse data to export")

        doc = Document()

        # Build title with library name and shelfmark
        shelfmark = browse_data.get('shelfmark', '')
        library_name = browse_data.get('library_name', '')

        # Document title: Library, Shelfmark (or just Shelfmark)
        if library_name and shelfmark:
            doc_title = f"{library_name}, {shelfmark}"
        elif shelfmark:
            doc_title = shelfmark
        else:
            doc_title = 'Genizah Manuscript'

        doc.add_heading(doc_title, 0)

        # Title (Hebrew)
        if browse_data.get('title'):
            add_hebrew_paragraph(doc, browse_data['title'])

        # System ID
        if browse_data.get('sys_id'):
            doc.add_paragraph(f"System ID: {browse_data['sys_id']}")

        doc.add_paragraph("_" * 60)

        # Text content
        if browse_data.get('view_all') and browse_data.get('pages'):
            doc.add_heading('Full Manuscript', 2)
            for page_data in browse_data['pages']:
                doc.add_heading(f"Page {page_data.get('p_num', '?')}", 3)
                if page_data.get('text'):
                    add_hebrew_paragraph(doc, page_data['text'])
        elif browse_data.get('text'):
            doc.add_heading(f"Page {browse_data.get('p_num', '?')}", 2)
            add_hebrew_paragraph(doc, browse_data['text'])

        add_word_credits(doc)

        # Filename: use shelfmark
        filename = make_safe_filename(shelfmark, default="manuscript") + ".docx"
        return save_document_to_bytes(doc), filename


# Create singleton instance (can be initialized with meta_mgr later)
_export_service: Optional[ExportService] = None


def get_export_service(meta_mgr=None) -> ExportService:
    """Get or create the export service singleton."""
    global _export_service
    if _export_service is None or (meta_mgr and _export_service.meta_mgr != meta_mgr):
        _export_service = ExportService(meta_mgr)
    return _export_service
