# -*- coding: utf-8 -*-
"""
Unified Export Service for GenizahSearch.

This module centralizes all export functionality to ensure:
1. Consistent RTL formatting for Hebrew text
2. Uniform credits and citation
3. Proper text sanitization
4. Reusable utilities across all export types (Excel, Word)

Author: GenizahSearch Team
"""

import io
import re
from typing import List, Dict, Any, Optional
from dataclasses import dataclass

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill

from docx import Document
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt


# Constants
HEBREW_FONT_NAME = "David"
CREDITS_TEXT = [
    'Generated by Dicta Genizah Search (Web Version)',
    'Data Source: MiDRASH Automatic Transcriptions (Stoekl Ben Ezra et al., 2025)',
    'Dataset: https://doi.org/10.5281/zenodo.17734473',
    'Citation: Stoekl Ben Ezra, D., Bambaci, L., Kiessling, B., Lapin, H., Ezer, N., Lolli, E., Rustow, M., Dershowitz, N., Kurar Barakat, B., Gogawale, S., Shmidman, A., Lavee, M., Siew, T., Raziel Kretzmer, V., Vasyutinsky Shapira, D., Olszowy-Schlanger, J., & Gila, Y. (2025). MiDRASH Automatic Transcriptions. Zenodo. https://doi.org/10.5281/zenodo.17734473',
]


# ============================================================================
# Text Processing Utilities
# Import from shared module for consistency between Desktop and Web
# ============================================================================

from shared_export_utils import (
    sanitize_text_for_excel,
    clean_text_single_line,
    remove_highlight_markers,
    make_safe_filename,
    encode_filename_for_header as encode_filename_for_header,  # re-exported for web.api
    # Phase 94 Wave 3 (MUST-FIX 94-03-B): contains_any_term + extract_search_terms
    # are no longer used inside export_search_results_excel (replaced by
    # build_rich_snippet_cell), but stay imported for backward-compat re-export
    # to test_export_service.py and any external callers.
    contains_any_term as contains_any_term,
    extract_search_terms as extract_search_terms,
)


def _resolve_result_full_text(result: Dict[str, Any]) -> str:
    """Return full text for export, rehydrating compact session rows if needed."""
    full_text = result.get('full_text') or ''
    if full_text:
        return str(full_text)

    uid = result.get('uid') or ''
    if uid:
        try:
            from web.state import state as web_state
            searcher = getattr(web_state, 'searcher', None)
            if searcher and hasattr(searcher, 'get_full_text_by_id'):
                fetched = searcher.get_full_text_by_id(uid)
                if fetched:
                    return str(fetched)
        except Exception:
            pass

    return str(result.get('full_text_excerpt') or '')


def _resolve_result_display(result: Dict[str, Any], meta_mgr) -> tuple:
    """Return (shelfmark, title, library_code, library_name) for an export row.

    SEED-002 fixup (2026-05-19) — tier order updated after Codex review:

      Tier 1: row's ``display`` dict (non-empty) -> verbatim. Preserves
              back-compat for legacy live rows before export_state compaction.
      Tier 2: ``result['sys_id']`` -> meta_mgr. The compactor at
              ``web/export_state.py:_extract_sys_id_from_row`` synthesizes
              this from display.id / raw_header / uid before allowlist
              filtering, so it is the canonical identity channel for all
              post-compaction rows (text-search AND metadata-only).
      Tier 3: extract sys_id from ``raw_header`` via regex ``(99\\d{8,})``.
              Legacy fallback for rows that bypassed the compactor.
      Tier 4: extract sys_id from ``uid`` via
              ``meta_mgr.parse_full_id_components`` -> meta_mgr lookups.
              Legacy fallback for rows that bypassed the compactor AND have
              a sys-id-bearing uid (NOT the production text-search shape,
              which uses ``IE..._P..._FL...`` -- see genizah_core.py:3617).
      Fallback: ('Unknown', '', '', '') when meta_mgr is None or no tier
                yields a sys_id. When a sys_id is known but meta_mgr lookups
                return Unknown, shelfmark falls back to ``ID: {sys_id}``,
                mirroring ``MetadataManager.get_display_data`` at
                ``genizah_core.py:4925``.

    library_name is resolved via the existing ``core_get_library_display``
    helper, with the library_code as the fallback when localization fails.
    """
    if not isinstance(result, dict):
        return ('Unknown', '', '', '')

    display = result.get('display') if isinstance(result.get('display'), dict) else None
    if display:
        shelfmark = display.get('shelfmark', '') or 'Unknown'
        title = display.get('title', '') or ''
        library_code = display.get('library_code', '') or ''
    else:
        if not meta_mgr:
            return ('Unknown', '', '', '')

        # Tier 2: explicit sys_id field synthesized by the compactor. This is
        # the path the vast majority of compacted rows take.
        sys_id_candidate = result.get('sys_id')
        sys_id = sys_id_candidate if isinstance(sys_id_candidate, str) else ''

        # Tier 3: raw_header regex (legacy fallback when compactor didn't run)
        if not sys_id:
            raw_header = result.get('raw_header', '') or ''
            if raw_header:
                try:
                    m = re.search(r'(99\d{8,})', raw_header)
                    if m:
                        sys_id = m.group(1)
                except Exception:
                    sys_id = ''

        # Tier 4: uid parsing (legacy fallback for sys-id-bearing uids)
        if not sys_id:
            uid = result.get('uid', '') or ''
            if uid:
                try:
                    parsed = meta_mgr.parse_full_id_components(uid) or {}
                    sys_id = parsed.get('sys_id') or ''
                except Exception:
                    sys_id = ''

        if not sys_id:
            return ('Unknown', '', '', '')

        # meta_mgr lookups with graceful per-call fallback. When meta_mgr has
        # the sys_id but no shelfmark (rare -- typically a synthetic row whose
        # libraries.csv entry got mangled), fall back to "ID: {sys_id}"
        # matching genizah_core.MetadataManager.get_display_data.
        try:
            meta = meta_mgr.get_meta_for_id(sys_id)
            if isinstance(meta, tuple) and len(meta) >= 2:
                shelfmark = meta[0] or f'ID: {sys_id}'
                title = meta[1] or ''
            else:
                shelfmark, title = f'ID: {sys_id}', ''
        except Exception:
            shelfmark, title = f'ID: {sys_id}', ''
        try:
            library_code = meta_mgr.get_library_for_id(sys_id) or ''
        except Exception:
            library_code = ''

    # Resolve library display name via the existing helper (handles
    # localization + has its own library_code fallback).
    library_name = ''
    if library_code:
        try:
            from genizah_core import get_library_display as core_get_library_display
            from web.translations import get_language
            library_name = core_get_library_display(
                library_code, short=False, lang=get_language()
            ) or library_code
        except Exception:
            library_name = library_code

    return (shelfmark, title, library_code, library_name)


# ============================================================================
# Word Document RTL Utilities
# ============================================================================

def set_paragraph_rtl(paragraph):
    """Set RTL direction and right alignment for a paragraph containing Hebrew text."""
    paragraph.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT
    paragraph.paragraph_format.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT
    ppr = paragraph._p.get_or_add_pPr()
    bidi = ppr.find(qn("w:bidi"))
    if bidi is None:
        bidi = OxmlElement("w:bidi")
        ppr.append(bidi)
    bidi.set(qn("w:val"), "1")


def set_run_rtl_font(run, font_size: Optional[int] = None):
    """Set Hebrew-compatible font for a run and mark it as RTL."""
    run.font.name = HEBREW_FONT_NAME
    r = run._r
    rPr = r.get_or_add_rPr()

    # Set cs (complex script) font for Hebrew
    cs_font = rPr.find(qn("w:rFonts"))
    if cs_font is None:
        cs_font = OxmlElement("w:rFonts")
        rPr.insert(0, cs_font)
    cs_font.set(qn("w:cs"), HEBREW_FONT_NAME)
    cs_font.set(qn("w:ascii"), HEBREW_FONT_NAME)
    cs_font.set(qn("w:hAnsi"), HEBREW_FONT_NAME)

    # Mark as RTL text
    rtl = rPr.find(qn("w:rtl"))
    if rtl is None:
        rtl = OxmlElement("w:rtl")
        rPr.append(rtl)

    if font_size:
        run.font.size = Pt(font_size)


def add_hebrew_paragraph(doc: Document, text: str, bold: bool = False, font_size: Optional[int] = None) -> None:
    """Add a right-aligned Hebrew paragraph to a Word document."""
    p = doc.add_paragraph()
    run = p.add_run(text)
    if bold:
        run.bold = True
    set_run_rtl_font(run, font_size)
    set_paragraph_rtl(p)


def add_highlighted_hebrew_paragraph(doc: Document, text: str) -> None:
    """
    Add a Hebrew paragraph with highlighted terms (marked with *).
    Text between * markers will be bold with yellow highlight.
    """
    p = doc.add_paragraph()
    parts = text.split('*')
    is_highlighted = False

    for i, part in enumerate(parts):
        if not part:
            is_highlighted = not is_highlighted
            continue
        run = p.add_run(part)
        set_run_rtl_font(run)
        if is_highlighted:
            run.bold = True
            # Add yellow highlight
            rPr = run._r.get_or_add_rPr()
            highlight = OxmlElement('w:highlight')
            highlight.set(qn('w:val'), 'yellow')
            rPr.append(highlight)
        is_highlighted = not is_highlighted

    set_paragraph_rtl(p)


def add_word_credits(doc: Document) -> None:
    """Add standard credits section to a Word document."""
    doc.add_page_break()
    doc.add_heading('Credits', 1)
    doc.add_paragraph(CREDITS_TEXT[0])
    doc.add_paragraph(CREDITS_TEXT[1])
    doc.add_paragraph(f'Dataset available at: {CREDITS_TEXT[2].replace("Dataset: ", "")}')
    doc.add_paragraph()
    citation_p = doc.add_paragraph('Full Citation: ')
    citation_run = citation_p.add_run(CREDITS_TEXT[3].replace('Citation: ', ''))
    citation_run.italic = True


# ============================================================================
# Excel Utilities
# ============================================================================

@dataclass
class ExcelColumnConfig:
    """Configuration for an Excel column."""
    header: str
    width: int
    alignment: str  # 'rtl', 'ltr', 'center'
    highlight_on_match: bool = False


def create_excel_workbook(
    sheet_name: str = "Results",
    rtl_sheet: bool = True
) -> tuple:
    """
    Create a new Excel workbook with basic configuration.
    Returns (workbook, worksheet).
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_name[:31]  # Excel sheet name limit
    if rtl_sheet:
        ws.sheet_view.rightToLeft = True
    return wb, ws


def style_excel_header(ws, headers: List[str]) -> None:
    """Apply standard header styling to the first row."""
    ws.append(headers)
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="4F81BD", end_color="4F81BD", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center")

    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment


def set_excel_column_widths(ws, widths: Dict[str, int]) -> None:
    """Set column widths. Keys are column letters (A, B, C, ...)."""
    for col_letter, width in widths.items():
        ws.column_dimensions[col_letter].width = width


def get_cell_alignment(align_type: str) -> Alignment:
    """Get an Alignment object based on alignment type."""
    if align_type == 'rtl':
        return Alignment(horizontal="right", vertical="top", wrap_text=False, readingOrder=2)
    elif align_type == 'center':
        return Alignment(horizontal="center", vertical="top")
    else:  # 'ltr'
        return Alignment(horizontal="left", vertical="top")


def add_excel_credits(ws) -> None:
    """Add standard credits section at the bottom of the worksheet."""
    ws.append([])
    ws.append([])
    credits_start_row = ws.max_row + 1
    ws.append(['Credits'])
    for credit_line in CREDITS_TEXT:
        ws.append([credit_line])

    # Style credits
    credits_font = Font(italic=True, color="555555")
    for row_idx in range(credits_start_row, ws.max_row + 1):
        cell = ws.cell(row=row_idx, column=1)
        cell.font = credits_font


def save_workbook_to_bytes(wb) -> bytes:
    """Save workbook to a bytes buffer and return the content."""
    stream = io.BytesIO()
    wb.save(stream)
    stream.seek(0)
    return stream.read()


def save_document_to_bytes(doc: Document) -> bytes:
    """Save Word document to a bytes buffer and return the content."""
    stream = io.BytesIO()
    doc.save(stream)
    stream.seek(0)
    return stream.read()


# ============================================================================
# High-Level Export Functions
# ============================================================================

class ExportService:
    """
    Unified service for exporting search results, lists, and other data.
    Ensures consistent formatting and error handling across all exports.
    """

    def __init__(self, meta_mgr=None):
        """
        Initialize the export service.

        Args:
            meta_mgr: MetadataManager instance for resolving shelfmarks/titles.
        """
        self.meta_mgr = meta_mgr

    def get_metadata(self, sys_id: str) -> tuple:
        """Get shelfmark and title for a system ID."""
        if not sys_id or not self.meta_mgr:
            return ('Unknown', '')
        try:
            shelfmark, title = self.meta_mgr.get_meta_for_id(sys_id)
            return (shelfmark or 'Unknown', title or '')
        except Exception:
            return ('Unknown', '')  # Metadata extraction failed; return fallback values

    def get_library_code(self, sys_id: str) -> str:
        """Get library code for a system ID."""
        if not sys_id or not self.meta_mgr:
            return ''
        try:
            return self.meta_mgr.get_library_for_id(sys_id) or ''
        except Exception:
            return ''  # Lookup failed; return empty string

    def get_library_display(self, library_code: str, short: bool = True) -> str:
        """Get library display name from code."""
        if not library_code:
            return ''
        try:
            from genizah_core import get_library_display as core_get_library_display
            from web.translations import get_language
            return core_get_library_display(library_code, short=short, lang=get_language())
        except Exception:
            return library_code  # Fallback to code itself

    def export_search_results_excel(
        self,
        results: List[Dict[str, Any]],
        search_query: str = "",
        *,
        # Phase 94 EXPORT-META-06 — enrichment signals from session payload.
        transcription_sys_ids: Optional[set] = None,
        printed_ids: Optional[set] = None,
        result_domains: Optional[Dict[str, List[str]]] = None,
        # Phase 94 EXPORT-META-05/D-04 — UI lang for conditional sheet RTL.
        # Content is always English per D-04; lang ONLY controls view direction.
        lang: str = 'en',
    ) -> tuple:
        """
        Export search results to a 3-sheet Excel workbook.

        Phase 94 EXPORT-META Wave 3: produces a 3-sheet workbook consisting of:

        1. **Search Results** (default-active per D-03) — unified 12-column
           main sheet per D-01. Sheet was renamed from ``"Genizah Results"``
           to ``"Search Results"`` in smoke verification round 2 (2026-05-21):
           ['System ID', 'Library', 'Shelfmark', 'Title', 'Image/Page',
            'Source', 'Snippet', 'Full Text', 'Has PGP', 'Is Printed',
            'Domains', 'IIIF Manifest'].
           Snippet column uses rich-text rendering per D-14 via
           ``shared_export_utils.build_rich_snippet_cell``.
           IIIF Manifest column is DEFERRED per D-13 (header present, cells
           empty). Per-page IIIF resolution would require per-row plumbing
           not warranted for this phase; the sys_id-scoped Library Viewer
           URL on the Manuscripts sub-sheet provides reachability instead.

        2. **Manuscripts** (dossier sub-sheet) — one row per UNIQUE sys_id
           via :func:`shared.export_dossier.build_manuscript_row` (14 columns).
           First-occurrence dedupe per D-12.

        3. **Bibliography** (sub-sheet) — one row per FJMS bib entry via
           :func:`shared.export_dossier.build_bibliography_rows` (8 columns).
           Zero rows when sys_id has no bib entries.

        Conditional RTL per D-04: ``lang == 'he'`` -> all 3 sheets RTL;
        otherwise LTR. Sheet name is ``"Search Results"`` (English) /
        ``"תוצאות חיפוש"`` (Hebrew) per smoke verification round 2
        (2026-05-21); previously ``"Genizah Results"`` / ``"תוצאות גניזה"``.
        Cross-app parity with desktop Wave 4 preserved via shared
        :func:`shared.export_dossier.sheet_titles`.

        Library name on all sheets is hard-pinned English per D-04 / Pattern
        1.8 / Shared Pattern F — routes through
        ``genizah_core.get_library_display(code, short=False, lang='en')``
        directly, bypassing the UI-lang-aware instance method
        :meth:`get_library_display`.

        Args:
            results: search result list (live or compacted).
            search_query: original query string (used for filename only).
            transcription_sys_ids: set of sys_ids with PGP transcription —
                Has PGP column renders 'Yes' / empty per row (D-06).
            printed_ids: set of sys_ids known to be printed — Is Printed
                column renders 'Yes' / empty per row (D-06).
            result_domains: ``{sys_id: [domain_str, ...]}`` mapping;
                Domains column renders pipe-joined string per D-05.
            lang: UI language ('he' or 'en'). Controls sheet view direction
                only; content stays English regardless.

        Returns:
            (bytes, filename) tuple.
        """
        if not results:
            raise ValueError("No results to export")

        from shared.export_dossier import (
            build_manuscript_row, build_bibliography_rows,
            main_header_row, manuscript_header_row, bibliography_header_row,
            sheet_titles,
        )
        from shared_export_utils import build_rich_snippet_cell
        from genizah_core import get_library_display as core_get_library_display

        rtl = (lang == 'he')
        _trans_set = set(transcription_sys_ids or [])
        _printed_set = set(printed_ids or [])
        _domains_map = dict(result_domains or {})

        # MUST-FIX 94-03-B: the legacy ``extract`` term-binding pattern is
        # REMOVED from the restructured function body. The new Snippet column
        # uses ``build_rich_snippet_cell`` (Wave 1) which operates on the
        # snippet's ``*``-markers directly, not on a pre-extracted terms list.
        # Leaving the binding in place would trigger Ruff F841 (unused-
        # variable). The term-extractor helper itself stays defined and
        # re-exported in ``shared_export_utils`` for other callers.

        # --- Build the meta_resolver callable (Codex SHOULD-FIX 8) ---
        # Maps sys_id -> {shelfmark, title, library_code, library_name};
        # library_name is hard-pinned English per D-04 / Pattern 1.8 / Shared
        # Pattern F. NEVER routes through self.get_library_display (which
        # consults UI lang) on the dossier path.
        meta_mgr = self.meta_mgr

        def _meta_resolver(sys_id):
            if not sys_id or meta_mgr is None:
                return None
            try:
                meta = meta_mgr.get_meta_for_id(sys_id)
                if isinstance(meta, tuple) and len(meta) >= 2:
                    shelf, title = (meta[0] or f'ID: {sys_id}'), (meta[1] or '')
                else:
                    shelf, title = f'ID: {sys_id}', ''
            except Exception:
                shelf, title = f'ID: {sys_id}', ''
            try:
                lib_code = meta_mgr.get_library_for_id(sys_id) or ''
            except Exception:
                lib_code = ''
            try:
                # D-04 REVISED (2026-05-20): library_name follows ``lang``.
                # Hebrew UI -> Hebrew library name (with English fallback inside
                # get_library_display) via LIBRARY_CODES_HE; English UI -> English.
                lib_name = (
                    core_get_library_display(lib_code, short=False, lang=lang)
                    if lib_code else ''
                )
            except Exception:
                lib_name = lib_code  # Graceful fallback to code (MUST-FIX 94-01-B).
            return {
                'shelfmark': shelf,
                'title': title,
                'library_code': lib_code,
                'library_name': lib_name,
            }

        # --- Workbook + 3 sheets ---
        # D-04 REVISED (2026-05-20): sheet titles are localized via sheet_titles(lang).
        # MUST-FIX 94-03-E (English-locked sheet name) is SUPERSEDED by this
        # bilingual revision; the cross-parity test still passes because it
        # builds both workbooks with the SAME lang (default 'en').
        _titles = sheet_titles(lang)
        wb, ws_main = create_excel_workbook(_titles['main'], rtl_sheet=rtl)
        ws_manu = wb.create_sheet(title=_titles['manuscripts'])
        ws_bib = wb.create_sheet(title=_titles['bibliography'])
        ws_manu.sheet_view.rightToLeft = rtl
        ws_bib.sheet_view.rightToLeft = rtl

        # --- Main sheet: unified 12-column order per D-01, bilingual headers ---
        main_headers = main_header_row(lang)
        style_excel_header(ws_main, main_headers)
        set_excel_column_widths(ws_main, {
            'A': 18, 'B': 25, 'C': 22, 'D': 35,
            'E': 14, 'F': 14, 'G': 50, 'H': 80,
            'I': 10, 'J': 12, 'K': 25, 'L': 30,
        })

        rtl_align = get_cell_alignment('rtl')
        ltr_align = get_cell_alignment('ltr')
        center_align = get_cell_alignment('center')

        for res in results:
            # SEED-002 fixup: rehydrate display fields from uid via meta_mgr
            # if the row is compacted (no display dict). Legacy rows with a
            # non-empty display dict are returned verbatim by the helper.
            shelfmark_live, title_live, _library_code, library_name_live = (
                _resolve_result_display(res, self.meta_mgr)
            )

            display_dict = res.get('display') if isinstance(res.get('display'), dict) else {}
            display_dict = display_dict or {}

            # Resolve sys_id for the "System ID" column. SEED-002 fixup tier
            # order matches _resolve_result_display.
            sys_id_for_cell = display_dict.get('id') or ''
            if not sys_id_for_cell:
                explicit_sys = res.get('sys_id')
                if isinstance(explicit_sys, str):
                    sys_id_for_cell = explicit_sys
            if not sys_id_for_cell:
                raw_header = res.get('raw_header', '') or ''
                if raw_header:
                    m = re.search(r'(99\d{8,})', raw_header)
                    if m:
                        sys_id_for_cell = m.group(1)
            if not sys_id_for_cell and self.meta_mgr:
                try:
                    parsed = self.meta_mgr.parse_full_id_components(
                        res.get('uid', '') or ''
                    ) or {}
                    sys_id_for_cell = parsed.get('sys_id') or ''
                except Exception:
                    sys_id_for_cell = ''

            # D-04 REVISED (2026-05-20): library_name follows ``lang``.
            # When lang == 'he' the row shows the Hebrew library name (via
            # LIBRARY_CODES_HE in get_library_display); when lang == 'en' the
            # English name. `library_name_live` from `_resolve_result_display`
            # routes through UI lang too, but we re-resolve via the lang-aware
            # core helper for explicit determinism on this path.
            lib_code_for_cell = ''
            try:
                if self.meta_mgr and sys_id_for_cell:
                    raw_lib = self.meta_mgr.get_library_for_id(sys_id_for_cell)
                    if isinstance(raw_lib, str):
                        lib_code_for_cell = raw_lib
            except Exception:
                lib_code_for_cell = ''
            if not lib_code_for_cell:
                disp_lib = display_dict.get('library_code')
                if isinstance(disp_lib, str):
                    lib_code_for_cell = disp_lib or ''
            try:
                library_name = (
                    core_get_library_display(lib_code_for_cell, short=False, lang=lang)
                    if lib_code_for_cell else ''
                )
            except Exception:
                library_name = lib_code_for_cell or (
                    library_name_live if isinstance(library_name_live, str) else ''
                )

            # MUST-FIX 94-03-A: Image/Page + Source survive compaction via
            # _SEARCH_ROW_ALLOWLIST extension + _compact_search_result_row
            # synthesis (web/export_state.py). Bounded fallback: live rows
            # expose display.img/display.source; compacted rows expose
            # top-level img/source. Either path yields non-empty cells.
            img_page = display_dict.get('img') or res.get('img') or ''
            source_label = display_dict.get('source') or res.get('source') or ''

            # MUST-FIX 94-03-D: snippet read after compaction.
            # _SEARCH_ROW_ALLOWLIST keeps only 'snippet' (which already
            # carries the *...* markers from genizah_core.highlight());
            # 'raw_file_hl' is STRIPPED during compaction so the legacy
            # `or res.get('raw_file_hl')` fallback was dead code for
            # compacted rows. Live rows also populate 'snippet' identically,
            # so dropping the fallback is safe.
            snippet_raw = res.get('snippet') or ''
            full_text = clean_text_single_line(_resolve_result_full_text(res))[:32000]

            # D-01 / D-05 / D-06 — new appended columns.
            has_pgp_cell = 'Yes' if (sys_id_for_cell and sys_id_for_cell in _trans_set) else ''
            is_printed_cell = 'Yes' if (sys_id_for_cell and sys_id_for_cell in _printed_set) else ''
            domains_list = _domains_map.get(sys_id_for_cell, []) or []
            domains_cell = '|'.join(d for d in domains_list if d)
            # IIIF Manifest column DEFERRED per D-13 — header present, cells empty.
            iiif_cell = ''

            row_cells = [
                sanitize_text_for_excel(sys_id_for_cell),
                sanitize_text_for_excel(library_name),
                sanitize_text_for_excel(shelfmark_live),
                sanitize_text_for_excel(title_live),
                sanitize_text_for_excel(img_page),
                sanitize_text_for_excel(source_label),
                None,  # Snippet — written via build_rich_snippet_cell below.
                sanitize_text_for_excel(full_text),
                has_pgp_cell,
                is_printed_cell,
                sanitize_text_for_excel(domains_cell),
                iiif_cell,
            ]
            ws_main.append(row_cells)
            current_row = ws_main.max_row

            # Snippet column (col 7) gets rich-text rendering per D-14.
            ws_main.cell(
                row=current_row, column=7,
                value=build_rich_snippet_cell(snippet_raw, sanitize_text_for_excel),
            )

            # Per-cell alignment (existing pattern).
            ws_main.cell(row=current_row, column=1).alignment = ltr_align  # System ID
            ws_main.cell(row=current_row, column=2).alignment = ltr_align  # Library (English)
            ws_main.cell(row=current_row, column=3).alignment = rtl_align if rtl else ltr_align  # Shelfmark
            ws_main.cell(row=current_row, column=4).alignment = rtl_align if rtl else ltr_align  # Title
            ws_main.cell(row=current_row, column=5).alignment = ltr_align  # Image/Page
            ws_main.cell(row=current_row, column=6).alignment = ltr_align  # Source
            ws_main.cell(row=current_row, column=7).alignment = rtl_align if rtl else ltr_align  # Snippet
            ws_main.cell(row=current_row, column=8).alignment = rtl_align if rtl else ltr_align  # Full Text
            ws_main.cell(row=current_row, column=9).alignment = center_align  # Has PGP
            ws_main.cell(row=current_row, column=10).alignment = center_align  # Is Printed
            ws_main.cell(row=current_row, column=11).alignment = ltr_align  # Domains
            ws_main.cell(row=current_row, column=12).alignment = ltr_align  # IIIF Manifest

        add_excel_credits(ws_main)

        # --- Manuscripts sub-sheet (D-02 / D-03 / D-12) ---
        # Dedupe sys_ids in first-occurrence order per D-12.
        seen = set()
        unique_sys_ids = []
        for r in results:
            sid_disp = r.get('display') if isinstance(r.get('display'), dict) else {}
            sid = (sid_disp or {}).get('id') or r.get('sys_id') or ''
            if sid and sid not in seen:
                seen.add(sid)
                unique_sys_ids.append(sid)

        # D-04 REVISED (2026-05-20): bilingual headers via manuscript_header_row(lang).
        style_excel_header(ws_manu, manuscript_header_row(lang))
        set_excel_column_widths(ws_manu, {
            'A': 18, 'B': 22, 'C': 25, 'D': 35, 'E': 30, 'F': 60,
            'G': 18, 'H': 14, 'I': 25, 'J': 25, 'K': 22, 'L': 50,
            'M': 30, 'N': 35,
        })
        for sid in unique_sys_ids:
            row = build_manuscript_row(sid, _meta_resolver, lang=lang)
            ws_manu.append([
                sanitize_text_for_excel(v) if isinstance(v, str) else v
                for v in row
            ])

        # --- Bibliography sub-sheet (D-02 / D-03) ---
        # D-04 REVISED (2026-05-20): bilingual headers via bibliography_header_row(lang).
        style_excel_header(ws_bib, bibliography_header_row(lang))
        set_excel_column_widths(ws_bib, {
            'A': 18, 'B': 22, 'C': 25, 'D': 40, 'E': 30, 'F': 12, 'G': 14, 'H': 20,
        })
        for sid in unique_sys_ids:
            for row in build_bibliography_rows(sid, _meta_resolver, lang=lang):
                ws_bib.append([
                    sanitize_text_for_excel(v) if isinstance(v, str) else v
                    for v in row
                ])

        # --- Default-active sheet per D-03 ---
        wb.active = wb.index(ws_main)

        filename = make_safe_filename(search_query) + ".xlsx"
        return save_workbook_to_bytes(wb), filename

    def export_search_results_word(
        self,
        results: List[Dict[str, Any]],
        search_query: str = ""
    ) -> tuple:
        """
        Export search results to Word format.

        Returns:
            (bytes, filename) tuple
        """
        if not results:
            raise ValueError("No results to export")

        doc = Document()
        title_text = f'Genizah Search Results: "{search_query}"' if search_query else 'Genizah Search Results'
        doc.add_heading(title_text, 0)

        for i, res in enumerate(results):
            # SEED-002: rehydrate display fields from uid via meta_mgr when
            # the row is compacted; legacy rows pass through unchanged.
            shelf, title, _library_code, library_name = _resolve_result_display(
                res, self.meta_mgr
            )

            # Build display header with library
            display_header = f"{library_name}, {shelf}" if library_name else shelf

            # Header with library and shelfmark
            p = doc.add_paragraph()
            run = p.add_run(f"{i+1}. {display_header}")
            run.bold = True
            set_run_rtl_font(run)
            if title:
                title_run = p.add_run(f" - {title}")
                set_run_rtl_font(title_run)
            set_paragraph_rtl(p)

            # Snippet with highlighting
            if res.get('snippet'):
                add_highlighted_hebrew_paragraph(doc, res['snippet'])

            # System ID: SEED-002 fixup tier order matches the Excel path:
            #   1. legacy display.id  2. row.sys_id  3. raw_header regex
            #   4. parse_full_id_components(uid) (legacy)
            legacy_display = res.get('display') if isinstance(res.get('display'), dict) else {}
            sys_id_for_text = (legacy_display or {}).get('id') or ''
            if not sys_id_for_text:
                explicit_sys = res.get('sys_id')
                if isinstance(explicit_sys, str):
                    sys_id_for_text = explicit_sys
            if not sys_id_for_text:
                raw_header = res.get('raw_header', '') or ''
                if raw_header:
                    m = re.search(r'(99\d{8,})', raw_header)
                    if m:
                        sys_id_for_text = m.group(1)
            if not sys_id_for_text and self.meta_mgr:
                try:
                    parsed = self.meta_mgr.parse_full_id_components(res.get('uid', '') or '') or {}
                    sys_id_for_text = parsed.get('sys_id') or ''
                except Exception:
                    sys_id_for_text = ''
            doc.add_paragraph(f"System ID: {sys_id_for_text}")
            doc.add_paragraph("_" * 40)

        add_word_credits(doc)

        # Filename with "search" suffix
        filename = make_safe_filename(search_query, default="genizah") + "_search.docx"
        return save_document_to_bytes(doc), filename

    def export_list_excel(
        self,
        list_id: str,
        list_name: str,
        items: List[Dict[str, Any]]
    ) -> tuple:
        """
        Export a personal list to Excel format.

        Returns:
            (bytes, filename) tuple
        """
        if not items:
            raise ValueError("List is empty")

        wb, ws = create_excel_workbook(list_name)

        headers = ["#", "Shelfmark", "Library", "Title", "System ID", "FL ID", "Notes", "Added"]
        style_excel_header(ws, headers)

        set_excel_column_widths(ws, {
            'A': 6, 'B': 25, 'C': 15, 'D': 35, 'E': 18, 'F': 12, 'G': 40, 'H': 18,
        })

        rtl_align = get_cell_alignment('rtl')
        ltr_align = get_cell_alignment('ltr')
        center_align = get_cell_alignment('center')

        for idx, item in enumerate(items, 1):
            sys_id = item.get('sys_id', '')
            shelfmark, title = self.get_metadata(sys_id)
            library_code = self.get_library_code(sys_id)
            # Get full library name
            library_name = self.get_library_display(library_code, short=False) if library_code else ''
            notes = clean_text_single_line(item.get('note', ''))

            row = [
                idx,
                sanitize_text_for_excel(shelfmark),
                sanitize_text_for_excel(library_name),
                sanitize_text_for_excel(title),
                sanitize_text_for_excel(sys_id),
                sanitize_text_for_excel(item.get('fl_id', '')),
                sanitize_text_for_excel(notes),
                sanitize_text_for_excel(item.get('added', '')),
            ]
            ws.append(row)

            current_row = ws.max_row
            ws.cell(row=current_row, column=1).alignment = center_align
            ws.cell(row=current_row, column=2).alignment = rtl_align
            ws.cell(row=current_row, column=3).alignment = ltr_align  # Library code is LTR
            ws.cell(row=current_row, column=4).alignment = rtl_align
            ws.cell(row=current_row, column=5).alignment = ltr_align
            ws.cell(row=current_row, column=6).alignment = ltr_align
            ws.cell(row=current_row, column=7).alignment = rtl_align
            ws.cell(row=current_row, column=8).alignment = ltr_align

        add_excel_credits(ws)

        safe_name = list_name.replace(' ', '_')
        filename = f"{safe_name}.xlsx"
        return save_workbook_to_bytes(wb), filename

    def export_parallels_excel(
        self,
        main_results: List[Dict[str, Any]],
        filtered_results: List[Dict[str, Any]] = None,
        source_text: str = ""
    ) -> tuple:
        """
        Export parallels results to Excel format.

        Returns:
            (bytes, filename) tuple
        """
        if not main_results and not filtered_results:
            raise ValueError("No parallels results to export")

        wb, ws = create_excel_workbook("Parallels Results")

        headers = ["#", "Shelfmark", "Library", "Title", "Score", "Source Context", "Manuscript Match", "Filtered"]
        style_excel_header(ws, headers)

        set_excel_column_widths(ws, {
            'A': 6, 'B': 25, 'C': 15, 'D': 35, 'E': 10, 'F': 50, 'G': 60, 'H': 10,
        })

        rtl_align = get_cell_alignment('rtl')
        ltr_align = get_cell_alignment('ltr')
        center_align = get_cell_alignment('center')

        def add_results(results: List[Dict], start_idx: int, is_filtered: bool) -> int:
            for idx, item in enumerate(results, start_idx):
                # SEED-002: tier-3 raw_header fallback inside the helper
                # handles legacy fixtures; tier-2 uid path handles
                # post-Task-1 compacted rows that may still carry raw_header.
                shelfmark, title, _library_code, library_name = _resolve_result_display(
                    item, self.meta_mgr
                )

                source_ctx = clean_text_single_line(remove_highlight_markers(item.get('source_ctx', '')))
                ms_text = clean_text_single_line(remove_highlight_markers(item.get('text', '')))

                row = [
                    idx,
                    sanitize_text_for_excel(shelfmark),
                    sanitize_text_for_excel(library_name),
                    sanitize_text_for_excel(title),
                    item.get('score', 0),
                    sanitize_text_for_excel(source_ctx),
                    sanitize_text_for_excel(ms_text),
                    'Yes' if is_filtered else '',
                ]
                ws.append(row)

                current_row = ws.max_row
                ws.cell(row=current_row, column=1).alignment = center_align  # #
                ws.cell(row=current_row, column=2).alignment = rtl_align     # Shelfmark
                ws.cell(row=current_row, column=3).alignment = ltr_align     # Library
                ws.cell(row=current_row, column=4).alignment = rtl_align     # Title
                ws.cell(row=current_row, column=5).alignment = center_align  # Score
                ws.cell(row=current_row, column=6).alignment = rtl_align     # Source Context
                ws.cell(row=current_row, column=7).alignment = rtl_align     # Manuscript Match
                ws.cell(row=current_row, column=8).alignment = center_align  # Filtered

            return start_idx + len(results)

        next_idx = add_results(main_results or [], 1, False)
        if filtered_results:
            add_results(filtered_results, next_idx, True)

        add_excel_credits(ws)

        # Filename: first words of source text + "_parallels"
        if source_text:
            filename_base = source_text[:30].strip()
            filename = make_safe_filename(filename_base, default="parallels") + "_parallels.xlsx"
        else:
            filename = "parallels_results.xlsx"

        return save_workbook_to_bytes(wb), filename

    def export_parallels_word(
        self,
        main_results: List[Dict[str, Any]],
        filtered_results: List[Dict[str, Any]] = None,
        source_text: str = ""
    ) -> tuple:
        """
        Export parallels results to Word format.

        Returns:
            (bytes, filename) tuple
        """
        if not main_results and not filtered_results:
            raise ValueError("No parallels results to export")

        doc = Document()

        # Build title with source text preview
        if source_text:
            # Take first ~50 chars of source text for title
            source_preview = source_text[:50].strip()
            if len(source_text) > 50:
                source_preview += "..."
            doc.add_heading(f'Parallels for: "{source_preview}"', 0)
        else:
            doc.add_heading('Genizah Parallels Search Results', 0)

        def add_results(results: List[Dict], start_idx: int, section_title: str = None) -> int:
            if section_title:
                doc.add_heading(section_title, 1)

            for idx, item in enumerate(results, start_idx):
                # SEED-002: use the shared rehydration helper (uid -> sys_id
                # for compacted rows; raw_header -> sys_id for legacy rows).
                shelfmark, title, _library_code, library_name = _resolve_result_display(
                    item, self.meta_mgr
                )

                # Build display header with library
                display_header = f"{library_name}, {shelfmark}" if library_name else shelfmark

                # Header
                p = doc.add_paragraph()
                shelf_run = p.add_run(f"{idx}. {display_header}")
                shelf_run.bold = True
                set_run_rtl_font(shelf_run)
                p.add_run(f" - Score: {item.get('score', 0)}")
                set_paragraph_rtl(p)

                # Title
                if title:
                    add_hebrew_paragraph(doc, title)

                # Source Context
                label_p = doc.add_paragraph()
                label_p.add_run("Source Context:").bold = True
                add_hebrew_paragraph(doc, remove_highlight_markers(item.get('source_ctx', '')))

                # Manuscript Match
                label_p2 = doc.add_paragraph()
                label_p2.add_run("Manuscript Match:").bold = True
                add_hebrew_paragraph(doc, remove_highlight_markers(item.get('text', '')))

                doc.add_paragraph("_" * 60)

            return start_idx + len(results)

        next_idx = add_results(main_results or [], 1)
        if filtered_results:
            add_results(filtered_results, next_idx, "Filtered Results (found in source texts)")

        add_word_credits(doc)

        # Filename: first words of source text + "_parallels"
        if source_text:
            # Take first ~30 chars for filename
            filename_base = source_text[:30].strip()
            filename = make_safe_filename(filename_base, default="parallels") + "_parallels.docx"
        else:
            filename = "parallels_results.docx"

        return save_document_to_bytes(doc), filename

    def export_browse_word(
        self,
        browse_data: Dict[str, Any]
    ) -> tuple:
        """
        Export browse page data to Word format.

        Returns:
            (bytes, filename) tuple
        """
        if not browse_data:
            raise ValueError("No browse data to export")

        doc = Document()

        # Build title with library name and shelfmark
        shelfmark = browse_data.get('shelfmark', '')
        library_name = browse_data.get('library_name', '')

        # Document title: Library, Shelfmark (or just Shelfmark)
        if library_name and shelfmark:
            doc_title = f"{library_name}, {shelfmark}"
        elif shelfmark:
            doc_title = shelfmark
        else:
            doc_title = 'Genizah Manuscript'

        doc.add_heading(doc_title, 0)

        # Title (Hebrew)
        if browse_data.get('title'):
            add_hebrew_paragraph(doc, browse_data['title'])

        # System ID
        if browse_data.get('sys_id'):
            doc.add_paragraph(f"System ID: {browse_data['sys_id']}")

        doc.add_paragraph("_" * 60)

        # Text content
        if browse_data.get('view_all') and browse_data.get('pages'):
            doc.add_heading('Full Manuscript', 2)
            for page_data in browse_data['pages']:
                doc.add_heading(f"Page {page_data.get('p_num', '?')}", 3)
                if page_data.get('text'):
                    add_hebrew_paragraph(doc, page_data['text'])
        elif browse_data.get('text'):
            doc.add_heading(f"Page {browse_data.get('p_num', '?')}", 2)
            add_hebrew_paragraph(doc, browse_data['text'])

        add_word_credits(doc)

        # Filename: use shelfmark
        filename = make_safe_filename(shelfmark, default="manuscript") + ".docx"
        return save_document_to_bytes(doc), filename


# Create singleton instance (can be initialized with meta_mgr later)
_export_service: Optional[ExportService] = None


def get_export_service(meta_mgr=None) -> ExportService:
    """Get or create the export service singleton."""
    global _export_service
    if _export_service is None or (meta_mgr and _export_service.meta_mgr != meta_mgr):
        _export_service = ExportService(meta_mgr)
    return _export_service
